/* GENERATED BY build-templates.js — DO NOT EDIT BY HAND.
   Edit the .json sources and run: node build-templates.js */
(function (root) {
  "use strict";
  root.GlyphTemplates = {
  "schema": 1,
  "note": "Template library, source of truth. Node, the CLI and the test suite read this file directly. The browser opens over file:// and cannot fetch .json, so run `node build-templates.js` to regenerate glyph-data.js after editing. The [ph-name] holes in a body are the parameters: a call binds them by name ([ph-name'value']) or by position (bare literals, in declaration order). An unbound hole becomes <needs> and does not block. The same [ph-name] may appear more than once in a body; every occurrence receives the same value.",
  "templates": {
    "germinate": {
      "gloss": "Walks every aspect of a situation as seeds and lays the path to the goal as a tree: roots=problem, trunk=effort, branches=resources, leaves=actions, fruit=goal.",
      "params": [
        { "name": "alvo", "ask": "what to germinate — the situation, subject or problem" },
        { "name": "criterio", "ask": "what to validate the result against" }
      ],
      "body": "[itr[ph-alvo`over seeds (every aspect of a situation, being it good, bad or neutral)`][val[lrn[impr`basic thinking`[skl`tree logic structure`[tgt`roots=problem,trunk=effort (anything that takes time and demands action),branches=resources(place, idea, person, method, any kind of),leaves = actions(effective denoted actions to be made to achieve the goal along the branch),fruit = the goal.`]]]][ph-criterio`the external criterion to validate against`]]"
    },

    "scientific-review": {
      "gloss": "Apply scientific rigour: criticise the target, rework it with what the critique found, and validate the result against an external standard.",
      "params": [
        { "name": "target", "ask": "what to put under scientific review" },
        { "name": "standard", "ask": "the external standard to hold it to — method, evidence, reproducibility" }
      ],
      "body": "[crit[ph-target`what to put under scientific review`]][rwk`the target itself, corrected by what the critique found`][val`the reworked result`,[ph-standard`the external standard: method, evidence, reproducibility`]]"
    },

    "reinforce": {
      "gloss": "There is a must-follow rule. Raise its precedence and state why it holds, so it survives a long context.",
      "params": [
        { "name": "rule", "ask": "the rule that must be followed" },
        { "name": "why", "ask": "why it must hold" }
      ],
      "body": "[prio[mand[ph-rule`the rule that must be followed`]]][rsn[ph-why`why it must hold, so it is not dropped later`]]"
    },

    "insight": {
      "gloss": "Frame the situation and its limits first, then brainstorm one realistic way out — not a list of options.",
      "params": [
        { "name": "situation", "ask": "the situation to get out of" },
        { "name": "limits", "ask": "what the idea must respect" }
      ],
      "body": "[ctx[ph-situation`the situation to get out of`]][cnst[ph-limits`what the idea must respect`]][brst`one realistic way out, restricted by the constraints above — not a list of options`][real]"
    },

    "fertilize": {
      "gloss": "Add base context to a situation, surface the implicit details as seeds, rebuild the problem from them, and propose new resources. Companion to germinate.",
      "params": [
        { "name": "situation", "ask": "the situation to fertilize" },
        { "name": "known", "ask": "what is already established and must not be re-derived" }
      ],
      "body": "[ctx[ph-situation`the situation to fertilize`]][base[ph-known`what is already established and must not be re-derived`]][elab`seeds — the details the situation left implicit`][drvf`rebuild the roots (the problem) from those seeds`][prop`new resources to feed the branches — at least two, of different kinds: place, idea, person or method`]"
    },

    "best-of": {
      "gloss": "Compare candidates that share one context, score them against a stated condition, name the winner and return the points that justify it.",
      "params": [
        { "name": "context", "ask": "the context all candidates share" },
        { "name": "a", "ask": "first candidate" },
        { "name": "b", "ask": "second candidate" },
        { "name": "criterion", "ask": "the condition that decides the winner" }
      ],
      "body": "[ctx[ph-context`the context all candidates share`]][cmp[ph-a`first candidate`],[ph-b`second candidate`]][val`each candidate against the stated condition`,[ph-criterion`the condition that decides the winner`]][cncl`the winner`][rtnl`the points that justify the result`]"
    },

    "track": {
      "gloss": "Explain where a detail came from across a long context: where it entered, what changed it, where it stands now. For the small things a human lets slip.",
      "params": [
        { "name": "item", "ask": "the detail whose origin to explain" },
        { "name": "scope", "ask": "the stretch of conversation to trace through" }
      ],
      "body": "[ctx[ph-scope`the stretch of conversation to trace through`]][drvf[ph-item`the detail whose origin to explain`]][elab`the chain: where it entered, what changed it, where it stands now`]"
    }
  }
};
  root.GlyphRules = {
  "schema": 2,
  "note": "Semantic rule table. Data, not code: editing this file changes engine behaviour. Three rule kinds. `pair` fires when both commands land on the same target (siblings, or one an ancestor of the other). `order` fires when `then` appears before `first` among siblings. `precondition` fires when `target` is not preceded by any of `requiresBefore` in the same segment. Names prefixed with @ resolve through `classes`. Every rule carries a `suggest`: the repair shape, not just the complaint.",

  "classes": {
    "thinking": ["CLAR", "CRIT", "BRST", "GEN", "SUM", "ELAB"],
    "subject":  ["CTX", "TGT", "REF", "BASE", "INS", "SECTION", "BLOCK", "PT"],
    "condition": ["COND", "IF", "UNLS", "ONLYW", "EXC"]
  },

  "scope": {
    "sameTarget": "siblings under one parent, OR one is an ancestor of the other",
    "within": "a single segment (block). Does not cross `;`.",
    "exemptUnder": ["OVR", "BYP"],
    "exemptWhy": "Under an explicit [ovr] or [byp] the overlap was requested on purpose."
  },

  "rules": [
    { "id": "mand-opt", "kind": "pair", "a": "MAND", "b": "OPT", "severity": "fix",
      "label": "contradiction",
      "why": "mandatory and optional cannot both hold for the same thing",
      "suggest": "Drop one, or scope the optional part into its own block." },

    { "id": "alw-nev", "kind": "pair", "a": "ALW", "b": "NEV", "severity": "fix",
      "label": "contradiction",
      "why": "always and never are opposite quantifiers",
      "suggest": "subject + cond + instof — name the subject, state the condition that separates the two cases, and what replaces it." },

    { "id": "pos-ngt", "kind": "pair", "a": "POS", "b": "NGT", "severity": "fix",
      "label": "contradiction",
      "why": "opposite polarity on the same target",
      "suggest": "pos + cond + ngt — a condition has to separate the two polarities." },

    { "id": "true-fls", "kind": "pair", "a": "TRUE", "b": "FLS", "severity": "fix",
      "label": "contradiction",
      "why": "opposite truth value on the same target",
      "suggest": "Split into two targets, or put a condition between them." },

    { "id": "mand-dont", "kind": "pair", "a": "MAND", "b": "DONT", "severity": "fix",
      "label": "contradiction",
      "why": "requiring and forbidding the same thing",
      "suggest": "Keep the prohibition and drop the obligation, or scope them under different conditions." },

    { "id": "rmbr-frgt", "kind": "pair", "a": "RMBR", "b": "FRGT", "severity": "fix",
      "label": "contradiction",
      "why": "remembering to forget makes the block impossible to honour",
      "suggest": "rmbr + cond + val + frgt — state when to forget and against which criterion." },

    { "id": "req-deny", "kind": "pair", "a": "REQ", "b": "DENY", "severity": "fix",
      "label": "contradiction",
      "why": "requiring and denying the same thing",
      "suggest": "Pick one; if both are meant, separate them by condition." },

    { "id": "req-dont", "kind": "pair", "a": "REQ", "b": "DONT", "severity": "ask",
      "label": "redundancy",
      "why": "requiring a negation is already a prohibition — the pair restates itself",
      "suggest": "prio + dont — if the point is emphasis, raise the priority of the prohibition instead of duplicating it." },

    { "id": "ins-opt", "kind": "pair", "a": "INS", "b": "OPT", "severity": "note",
      "label": "weakening",
      "why": "an optional instruction lands at the back of the queue and may be dropped entirely",
      "suggest": "block << opt — scope the optional part into its own block instead of weakening the instruction itself." },

    { "id": "mand-avd", "kind": "pair", "a": "MAND", "b": "AVD", "severity": "ask",
      "label": "redundancy",
      "why": "avoiding a situation is a synonym of don't, so the obligation has nothing left to bind to",
      "suggest": "mand-ins + avd — chain the obligation onto an instruction, then state what to avoid." },

    { "id": "req-avd", "kind": "pair", "a": "REQ", "b": "AVD", "severity": "ask",
      "label": "tension",
      "why": "requiring something that is also to be avoided",
      "suggest": "Separate by condition, or drop one side." },

    { "id": "req-opt", "kind": "pair", "a": "REQ", "b": "OPT", "severity": "ask",
      "label": "tension",
      "why": "a requirement and an option over the same thing",
      "suggest": "Decide which one binds; optional requirements are not enforceable." },

    { "id": "req-depr", "kind": "pair", "a": "REQ", "b": "DEPR", "severity": "ask",
      "label": "tension",
      "why": "requiring something marked obsolete",
      "suggest": "Name the replacement with instof, or drop the deprecation mark." },

    { "id": "conf-skep", "kind": "pair", "a": "CONF", "b": "SKEP", "severity": "ask",
      "label": "tension",
      "why": "confirming and doubting the same point",
      "suggest": "Doubt first, confirm after — or split into two blocks." },

    { "id": "conf-ctrd", "kind": "pair", "a": "CONF", "b": "CTRD", "severity": "ask",
      "label": "tension",
      "why": "confirming and contradicting the same point",
      "suggest": "Separate by condition, or make the contradiction a hypothesis." },

    { "id": "mand-byp", "kind": "pair", "a": "MAND", "b": "BYP", "severity": "ask",
      "label": "tension",
      "why": "bypassing what was declared mandatory",
      "suggest": "Legitimate under [ovr]; outside it, one of the two is wrong." },

    { "id": "hyp-assm", "kind": "pair", "a": "HYP", "b": "ASSM", "severity": "ask",
      "label": "tension",
      "why": "assuming a hypothesis may not produce rational results — the thing under test is being taken as given",
      "suggest": "subject + hyp, or subject + assm — give each its own subject and keep them apart." },

    { "id": "clar-elab", "kind": "pair", "a": "CLAR", "b": "ELAB", "severity": "ask",
      "label": "tension",
      "why": "clarify (which absorbed simplify) and elaborate pull in opposite directions",
      "suggest": "Pick the direction, or elaborate first and clarify the result." },

    { "id": "sum-elab", "kind": "pair", "a": "SUM", "b": "ELAB", "severity": "ask",
      "label": "tension",
      "why": "summarising and elaborating the same thing",
      "suggest": "elab + sum — elaborate first, then summarise what came out." },

    { "id": "gen-elab", "kind": "pair", "a": "GEN", "b": "ELAB", "severity": "ask",
      "label": "tension",
      "why": "generalising and specifying (ELAB absorbed SPEC) the same thing",
      "suggest": "Pick the direction, or separate them by condition." },

    { "id": "elab-before-thinking", "kind": "order", "first": "ELAB", "then": "@thinking",
      "severity": "note", "label": "order",
      "why": "a topic and its elaboration do not justify each other when the thinking op comes first",
      "suggest": "elab + thinking — elaborate, then operate on what was elaborated." },

    { "id": "brst-needs-frame", "kind": "precondition", "target": "BRST",
      "requiresBefore": ["@subject", "@condition", "@thinking"],
      "severity": "ask", "label": "precondition",
      "why": "ideation is unpredictable without a frame in front of it",
      "suggest": "subject + brst — at minimum a context, condition or thinking op before the brainstorm." },

    { "id": "hyp-needs-subject", "kind": "precondition", "target": "HYP",
      "requiresBefore": ["@subject"],
      "severity": "ask", "label": "precondition",
      "why": "a hypothesis with no stated subject cannot be tested",
      "suggest": "subject + hyp" },

    { "id": "assm-needs-subject", "kind": "precondition", "target": "ASSM",
      "requiresBefore": ["@subject"],
      "severity": "ask", "label": "precondition",
      "why": "an assumption with no stated subject cannot be checked",
      "suggest": "subject + assm" }
  ],

  "notRules": [
    { "pair": "CMP + DIST", "why": "comparing and distinguishing are complementary, not opposed" },
    { "pair": "CRIT + IMPR", "why": "criticise then improve is the natural work sequence" },
    { "pair": "BRST + CAT", "why": "generate items, then group them" },
    { "pair": "ALW + COND", "why": "'always, under this condition' is scoping, not contradiction" },
    { "pair": "POS + CRIT", "why": "criticism can be positive" },
    { "pair": "EXC + INSTOF", "why": "exception and substitution coexist — PLANILHA_FUSOES, house 7" }
  ]
};
})(typeof self !== "undefined" ? self : this);
