[package]
name = "glyph-stores"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[dependencies]
glyph-vocab = { path = "../glyph-vocab" }

[build-dependencies]
glyph-util = { path = "../glyph-util" }
glyph-vocab = { path = "../glyph-vocab" }

[dev-dependencies]
glyph-util = { path = "../glyph-util" }
