/**
 * Builds the publishable glyph-markup skill folder from the repository.
 *
 *   node build-skill.js            write it
 *   node build-skill.js --check    verify it matches, write nothing
 *
 * The Regent's layout: SKILL.md at the root, the engine beside it, the
 * normative material in `references/`, and the examples NESTED below that
 * rather than beside it — nesting is the hierarchy written into the tree
 * instead of asserted in a sentence. Each level gates a read that is not always
 * needed: SKILL.md always loads, `references/` only when the norm is wanted,
 * `references/examples/` only when the norm was not enough.
 *
 * Everything except SKILL.md is GENERATED, and that is the point. A skill has
 * to be self-contained — it travels to accounts where nothing is installed —
 * so it must carry content, not references. Carrying content by hand is how the
 * copies diverge, which is exactly the defect the standing order is named after:
 * the installed skill has been teaching `[SECTION: n]`, a form this engine
 * rejects at `fix`, since v1.6, because a republish that was noted in the v1.7
 * changelist never happened.
 *
 * So the copies are stamped and checkable. `--check` rebuilds in memory and
 * compares, catching both a hand-edited copy and one left stale by a changed
 * source — the same mechanism as build-templates.js, for the same reason.
 *
 * SKILL.md is NOT generated: it is the skill's own prose. What is enforced is
 * that the version it declares matches the engine's, so it cannot go stale on
 * the one fact that made the installed copy dangerous.
 */

"use strict";


import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import path from "node:path";
const require = createRequire(import.meta.url);
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const fs = require("fs");

const HERE = __dirname;
const ROOT = path.join(__dirname, "..");
const GUIDE = path.join(ROOT, ".guidelines");
const SKILL = path.join(ROOT, "skills", "glyph-markup");

const CHECK = process.argv.indexOf("--check") !== -1;
const STALE = [];
import GlyphCore from "./glyph-parser.js";
const VERSION = GlyphCore.VERSION;

function banner(source, comment) {
  const line1 = "GENERATED by build-skill.js from " + source + " at engine " + VERSION +
                " — DO NOT EDIT BY HAND.";
  const line2 = "Edit the source in the glyph repository and run: node scripts/build-skill.js";
  if (comment === "js") return "/* " + line1 + "\n   " + line2 + " */\n";
  return "<!-- " + line1 + "\n     " + line2 + " -->\n\n";
}

/* D-01 - every published file lands together or none does. Same discipline as
   build-templates.js: write each to a sibling .tmp first, then rename them all,
   so a crash leaves the skill wholly old or wholly new. */
const WRITES = [];

function commitWrites() {
  const staged = [];
  try {
    WRITES.forEach(w => {
      fs.mkdirSync(path.dirname(w.full), { recursive: true });
      const tmp = w.full + ".tmp";
      fs.writeFileSync(tmp, w.content);
      staged.push({ tmp: tmp, full: w.full, rel: w.rel, len: w.content.length });
    });
  } catch (e) {
    staged.forEach(t => { try { fs.unlinkSync(t.tmp); } catch (e2) {} });
    throw e;
  }
  staged.forEach(t => {
    fs.renameSync(t.tmp, t.full);
    console.log("  ✓ " + t.rel + " (" + t.len + " bytes)");
  });
}

function emit(rel, content) {
  /* Normalise CRLF for the same reason build-templates.js does: the sources
     carry system line endings on Windows, the generated file then comes out
     mixed, and `git status` starts lying about a file nobody is supposed to
     edit. A --check that fails because git rewrote the line endings is a check
     people learn to ignore. */
  content = content.replace(/\r\n/g, "\n");
  const full = path.join(SKILL, rel);
  if (!CHECK) {
    /* D-01: staged, not written. A published skill half of one version and
       half of another is worse than one that failed to publish, because the
       harness reads it either way and nothing says which halves are which. */
    WRITES.push({ full: full, rel: rel, content: content });
    return;
  }
  let disk = null;
  try { disk = fs.readFileSync(full, "utf8"); }
  catch (e) { STALE.push(rel + ": missing"); return; }
  if (disk !== content)
    STALE.push(rel + (disk.length === content.length
      ? ": differs from a fresh build (same length — an edit in place)"
      : ": differs (" + disk.length + " on disk, " + content.length + " fresh)"));
  else console.log("  ✓ " + rel);
}

/* the engine itself: the skill can then prove behaviour instead of describing
   it, which is what stops a reader inferring a rule the engine does not have */
emit(path.join("scripts", "glyph-parser.js"),
     banner("scripts/glyph-parser.js", "js") +
     fs.readFileSync(path.join(HERE, "glyph-parser.js"), "utf8").replace(/\r\n/g, "\n"));

/* normative, at source level: the generic shape of the output and everything
   needed to explain it, including §11, the failure treatment */
["XML_REFERENCE.md", "GLOSSARY.md"].forEach(f =>
  emit(path.join("references", f),
       banner(".guidelines/" + f, "md") +
       fs.readFileSync(path.join(GUIDE, f), "utf8").replace(/\r\n/g, "\n")));

/* perishable, one level below: bound to one input and one engine version, and
   saying so. Generated from the conformance vectors so the two cannot drift —
   validator rule 10 of BUNDLE_TARGET is what catches a hand edit here. */
const ex = JSON.parse(fs.readFileSync(path.join(ROOT, "conformance", "examples.json"), "utf8"));
let md = banner("conformance/examples.json", "md") +
  "# Examples — perishable\n\n" +
  "Produced by engine **" + VERSION + "** from sources authored on " + ex.authored + ".\n\n" +
  "These illustrate; they do not define. `../XML_REFERENCE.md` is normative and\n" +
  "outranks anything here. An example is bound to one input and one engine\n" +
  "version, so it goes stale in a way the reference does not — if the two ever\n" +
  "disagree, the reference is right and this file needs regenerating.\n";
ex.cases.forEach(c => {
  md += "\n---\n\n## " + c.id + "\n\n```glyph\n" + c.src + "\n```\n\n```xml\n" + c.xml + "\n```\n";
  if (!c.roundTrips) md += "\n> Does not survive `fromXML`, by design — see `roundTripNote` in the vector.\n";
});
emit(path.join("references", "examples", "EXAMPLES.md"), md);

/* SKILL.md is authored, not generated. Only its version is enforced — the one
   fact whose staleness is what made the installed copy actively misleading. */
const skillMd = fs.readFileSync(path.join(SKILL, "SKILL.md"), "utf8");
const declared = (skillMd.match(/# Glyph Shorthand Markup Language \(v([0-9.]+)\)/) || [])[1];
if (declared !== VERSION)
  STALE.push("SKILL.md: declares v" + declared + ", engine is " + VERSION);
else console.log("  ✓ SKILL.md declares v" + VERSION);

if (CHECK) {
  if (STALE.length) {
    console.error("\nFAILED: the published skill does not match this repository.");
    STALE.forEach(s => console.error("  ✗ " + s));
    console.error("\nRun: node scripts/build-skill.js");
    process.exit(1);
  }
  console.log("\nThe skill matches a fresh build.");
} else {
  commitWrites();
  console.log("\nskills/glyph-markup is built at " + VERSION + " (" + WRITES.length +
              " file(s) committed together). Reinstall it for the harness to see it.");
}
