/* GENERATED BY build-templates.js — DO NOT EDIT BY HAND.
   Edit the .json sources and run: node build-templates.js */
(function (root) {
  "use strict";
  root.GlyphTemplates = {
  "schema": 1,
  "note": "Template library, source of truth. Node, the CLI and the test suite read this file directly. The browser opens over file:// and cannot fetch .json, so run `node build-templates.js` to regenerate glyph-data.js after editing. The [ph-name] holes in a body are the parameters: a call binds them by name ([ph-name'value']) or by position (bare literals, in declaration order). An unbound hole becomes <needs> and does not block. The same [ph-name] may appear more than once in a body; every occurrence receives the same value. A param may instead be marked \"repeat\": true (at most one per template) for a variadic hole: it is excluded from positional order (a fixed param declared after it would collide with however many repeats were supplied) and binds only through the call repeating [ph-name'v1'][ph-name'v2']..., each occurrence becoming one more sibling node where the hole sat. Zero repeats drops the hole from the output instead of leaving a <needs> — it is optional plurality on top of whatever fixed params already satisfy the template's minimum, not a required slot. See best-of's `more` param. A template may also carry `constraints`: each one names, in `forbid`, a class (\"@name\", resolved through glyph-rules.json's classes) or a bare command that must not appear inside that template's own expansion. It is checked only within that expansion, and an explicit [ovr]/[byp] around the offender exempts it — a preset de-limits the shape it promised, it does not wall the writer in. Keep constraint severity at `ask`: leaving a preset's shape is not broken syntax, so it must not be `fix`. See loop's `no-coarsen` / `no-exit`.",
  "templates": {
    "germinate": {
      "gloss": "Walks every aspect of a situation as seeds and lays the path to the goal as a tree: roots=problem, trunk=effort, branches=resources, leaves=actions, fruit=goal.",
      "params": [
        { "name": "alvo", "ask": "what to germinate — the situation, subject or problem" },
        { "name": "criterio", "ask": "what to validate the result against" }
      ],
      "body": "[itr[ph-alvo`over seeds (every aspect of a situation, being it good, bad or neutral)`][val[lrn[impr`basic thinking`[skl`tree logic structure`[tgt`roots=problem,trunk=effort (anything that takes time and demands action),branches=resources(place, idea, person, method, any kind of),leaves = actions(effective denoted actions to be made to achieve the goal along the branch),fruit = the goal.`]]]][ph-criterio`the external criterion to validate against`]]"
    },

    "scientific-review": {
      "gloss": "Apply scientific rigour: criticise the target, rework it with what the critique found, and validate the result against an external standard.",
      "params": [
        { "name": "target", "ask": "what to put under scientific review" },
        { "name": "standard", "ask": "the external standard to hold it to — method, evidence, reproducibility" }
      ],
      "body": "[crit[ph-target`what to put under scientific review`]][rwk`the target itself, corrected by what the critique found`][val`the reworked result`,[ph-standard`the external standard: method, evidence, reproducibility`]]"
    },

    "reinforce": {
      "gloss": "There is a must-follow rule. Raise its precedence and state why it holds, so it survives a long context.",
      "params": [
        { "name": "rule", "ask": "the rule that must be followed" },
        { "name": "why", "ask": "why it must hold" }
      ],
      "body": "[prio[mand[ph-rule`the rule that must be followed`]]][rsn[ph-why`why it must hold, so it is not dropped later`]]"
    },

    "insight": {
      "gloss": "Frame the situation and its limits first, then brainstorm one realistic way out — not a list of options.",
      "params": [
        { "name": "situation", "ask": "the situation to get out of" },
        { "name": "limits", "ask": "what the idea must respect" }
      ],
      "body": "[ctx[ph-situation`the situation to get out of`]][cnst[ph-limits`what the idea must respect`]][brst`one realistic way out, restricted by the constraints above — not a list of options`][real]"
    },

    "fertilize": {
      "gloss": "Add base context to a situation, surface the implicit details as seeds, rebuild the problem from them, and propose new resources. Companion to germinate.",
      "params": [
        { "name": "situation", "ask": "the situation to fertilize" },
        { "name": "known", "ask": "what is already established and must not be re-derived" }
      ],
      "body": "[ctx[ph-situation`the situation to fertilize`]][base[ph-known`what is already established and must not be re-derived`]][elab`seeds — the details the situation left implicit`][drvf`rebuild the roots (the problem) from those seeds`][prop`new resources to feed the branches — at least two, of different kinds: place, idea, person or method`]"
    },

    "best-of": {
      "gloss": "Compare candidates that share one context, score them against a stated condition, name the winner and return the points that justify it.",
      "params": [
        { "name": "context", "ask": "the context all candidates share" },
        { "name": "a", "ask": "first candidate" },
        { "name": "b", "ask": "second candidate" },
        { "name": "more", "ask": "an extra candidate beyond the first two — repeat the ph-more call once per extra candidate", "repeat": true },
        { "name": "criterion", "ask": "the condition that decides the winner" }
      ],
      "body": "[ctx[ph-context`the context all candidates share`]][cmp[ph-a`first candidate`],[ph-b`second candidate`],[ph-more`an extra candidate, repeated once per extra`]][val`each candidate against the stated condition`,[ph-criterion`the condition that decides the winner`]][cncl`the winner`][rtnl`the points that justify the result`]"
    },

    "loop": {
      "gloss": "Iterate on one target until a stated stop condition holds, deepening the detail on every pass instead of restating it. Each pass is checked for realism against the stop condition before the next one opens.",
      "params": [
        { "name": "target", "ask": "what to iterate on" },
        { "name": "pass", "ask": "what each pass must produce that the previous one did not" },
        { "name": "until", "ask": "the stop condition — what makes another pass unnecessary" }
      ],
      "body": "[itr[ph-target`what to iterate on`]][ins[ph-pass`what each pass must add that the previous one did not — go one level finer, do not restate`]][cond[ph-until`the stop condition: what makes another pass unnecessary`]][real`each pass against the stop condition, before opening the next one`]",
      "constraints": [
        { "id": "no-coarsen", "forbid": "@coarsen", "severity": "ask", "label": "regride o detalhe",
          "why": "o laço existe para aprofundar a cada passagem, e generalizar ou resumir desfaz o detalhe que a passagem anterior ganhou",
          "suggest": "elabore dentro da passagem; resuma ou generalize depois que [cond] fechar o laço, não no meio dele" },
        { "id": "no-exit", "forbid": "@exit", "severity": "ask", "label": "abandona o laço",
          "why": "trocar o alvo, cair no plano B ou esquecer o que veio antes dissolve a iteração que o preset abriu, em vez de completá-la",
          "suggest": "se a condição de parada é que está errada, corrija [cond]; trocar o alvo no meio começa um laço novo, não termina este" }
      ]
    },

    "track": {
      "gloss": "Explain where a detail came from across a long context: where it entered, what changed it, where it stands now. For the small things a human lets slip.",
      "params": [
        { "name": "item", "ask": "the detail whose origin to explain" },
        { "name": "scope", "ask": "the stretch of conversation to trace through" }
      ],
      "body": "[ctx[ph-scope`the stretch of conversation to trace through`]][drvf[ph-item`the detail whose origin to explain`]][elab`the chain: where it entered, what changed it, where it stands now`]"
    }
  }
};
  root.GlyphRules = {
  "schema": 2,
  "note": "Semantic rule table. Data, not code: editing this file changes engine behaviour. Three rule kinds. `pair` fires when both commands land on the same target (siblings, or one an ancestor of the other). `order` fires when `then` appears before `first` among siblings. `precondition` fires when `target` is not preceded by any of `requiresBefore` in the same segment. Names prefixed with @ resolve through `classes`. Every rule carries a `suggest`: the repair shape, not just the complaint.",

  "classes": {
    "thinking": ["CLAR", "CRIT", "BRST", "GEN", "SUM", "ELAB"],
    "subject":  ["CTX", "TGT", "REF", "CORE", "INS", "SECTION", "BLOCK", "PT"],
    "condition": ["COND", "IF", "UNLS", "ONLYIF", "ONLYW", "EXC", "SWITCH"],
    "coarsen": ["GEN", "SUM", "SIMP"],
    "exit": ["INSTOF", "FBK", "FRGT"]
  },

  "classNote": "`coarsen` and `exit` exist for template constraints (see glyph-templates.json), not for the rules below. `coarsen` is the direction that undoes detail: generalise, summarise, simplify. CLAR left this class in v1.1.0.0 — with the v1.7 fusion undone, clarifying means removing ambiguity, which often ADDS words rather than cutting them, so it is not a coarsening direction. `exit` is the direction that leaves the structure standing but stops using it: substitute the target, fall back, forget. Neither is wrong on its own — they are only worth flagging inside a preset that promised the opposite direction.",

  "scope": {
    "sameTarget": "siblings under one parent, OR one is an ancestor of the other",
    "within": "a single segment (block). Does not cross `;`.",
    "exemptUnder": ["OVR", "BYP"],
    "exemptWhy": "Under an explicit [ovr] or [byp] the overlap was requested on purpose."
  },

  "rules": [
    { "id": "mand-opt", "kind": "pair", "a": "MAND", "b": "OPT", "severity": "fix",
      "label": "contradiction",
      "why": "mandatory and optional cannot both hold for the same thing",
      "suggest": "Drop one, or scope the optional part into its own block." },

    { "id": "alw-nev", "kind": "pair", "a": "ALW", "b": "NEV", "severity": "fix",
      "label": "contradiction",
      "why": "always and never are opposite quantifiers",
      "suggest": "subject + cond + instof — name the subject, state the condition that separates the two cases, and what replaces it." },

    { "id": "pos-ngt", "kind": "pair", "a": "POS", "b": "NGT", "severity": "fix",
      "label": "contradiction",
      "why": "opposite polarity on the same target",
      "suggest": "pos + cond + ngt — a condition has to separate the two polarities." },

    { "id": "true-fls", "kind": "pair", "a": "TRUE", "b": "FLS", "severity": "fix",
      "label": "contradiction",
      "why": "opposite truth value on the same target",
      "suggest": "Split into two targets, or put a condition between them." },

    { "id": "mand-dont", "kind": "pair", "a": "MAND", "b": "DONT", "severity": "fix",
      "label": "contradiction",
      "why": "requiring and forbidding the same thing",
      "suggest": "Keep the prohibition and drop the obligation, or scope them under different conditions." },

    { "id": "rmbr-frgt", "kind": "pair", "a": "RMBR", "b": "FRGT", "severity": "fix",
      "label": "contradiction",
      "why": "remembering to forget makes the block impossible to honour",
      "suggest": "rmbr + cond + val + frgt — state when to forget and against which criterion." },

    { "id": "req-deny", "kind": "pair", "a": "REQ", "b": "DENY", "severity": "ask",
      "label": "tension",
      "why": "requiring something to exist while rejecting a route that reaches it — legitimate if the rejected route is not the only one, wrong if it is",
      "suggest": "Name the route that stays open, or drop one side.",
      "note": "Was severity `fix` and label `contradiction` through v1.0.9, when DENY meant refusing a proposal. In v1.1.0.0 DENY rejects the route to a result and REQ demands existence, so the two no longer collide by construction — GLOSSARY.md §6.6." },

    { "id": "req-dont", "kind": "pair", "a": "REQ", "b": "DONT", "severity": "ask",
      "label": "redundancy",
      "why": "requiring a negation is already a prohibition — the pair restates itself",
      "suggest": "prio + dont — if the point is emphasis, raise the priority of the prohibition instead of duplicating it." },

    { "id": "ins-opt", "kind": "pair", "a": "INS", "b": "OPT", "severity": "note",
      "label": "weakening",
      "why": "an optional instruction lands at the back of the queue and may be dropped entirely",
      "suggest": "block << opt — scope the optional part into its own block instead of weakening the instruction itself." },

    { "id": "mand-avd", "kind": "pair", "a": "MAND", "b": "AVD", "severity": "ask",
      "label": "redundancy",
      "why": "avoiding a situation is a synonym of don't, so the obligation has nothing left to bind to",
      "suggest": "mand-ins + avd — chain the obligation onto an instruction, then state what to avoid." },

    { "id": "req-avd", "kind": "pair", "a": "REQ", "b": "AVD", "severity": "ask",
      "label": "tension",
      "why": "requiring something that is also to be avoided",
      "suggest": "Separate by condition, or drop one side." },

    { "id": "req-opt", "kind": "pair", "a": "REQ", "b": "OPT", "severity": "ask",
      "label": "tension",
      "why": "a requirement and an option over the same thing",
      "suggest": "Decide which one binds; optional requirements are not enforceable." },

    { "id": "req-depr", "kind": "pair", "a": "REQ", "b": "DEPR", "severity": "ask",
      "label": "tension",
      "why": "requiring something marked obsolete",
      "suggest": "Name the replacement with instof, or drop the deprecation mark." },

    { "id": "conf-skep", "kind": "pair", "a": "CONF", "b": "SKEP", "severity": "ask",
      "label": "tension",
      "why": "confirming and doubting the same point",
      "suggest": "Doubt first, confirm after — or split into two blocks." },

    { "id": "conf-ctrd", "kind": "pair", "a": "CONF", "b": "CTRD", "severity": "ask",
      "label": "tension",
      "why": "confirming and contradicting the same point",
      "suggest": "Separate by condition, or make the contradiction a hypothesis." },

    { "id": "mand-byp", "kind": "pair", "a": "MAND", "b": "BYP", "severity": "ask",
      "label": "tension",
      "why": "bypassing what was declared mandatory",
      "suggest": "Legitimate under [ovr]; outside it, one of the two is wrong." },

    { "id": "hyp-assm", "kind": "pair", "a": "HYP", "b": "ASSM", "severity": "ask",
      "label": "tension",
      "why": "assuming a hypothesis may not produce rational results — the thing under test is being taken as given",
      "suggest": "subject + hyp, or subject + assm — give each its own subject and keep them apart." },

    { "id": "simp-elab", "kind": "pair", "a": "SIMP", "b": "ELAB", "severity": "ask",
      "label": "tension",
      "why": "simplify cuts and elaborate adds — opposite directions on the same target",
      "suggest": "Pick the direction, or elaborate first and simplify the result." },

    { "id": "sum-elab", "kind": "pair", "a": "SUM", "b": "ELAB", "severity": "ask",
      "label": "tension",
      "why": "summarising and elaborating the same thing",
      "suggest": "elab + sum — elaborate first, then summarise what came out." },

    { "id": "gen-elab", "kind": "pair", "a": "GEN", "b": "ELAB", "severity": "ask",
      "label": "tension",
      "why": "generalising drops the particulars that elaborating is adding",
      "suggest": "Pick the direction, or separate them by condition." },

    { "id": "gen-spec", "kind": "pair", "a": "GEN", "b": "SPEC", "severity": "ask",
      "label": "tension",
      "why": "a general pattern and a detailed specification of the same thing pull apart",
      "suggest": "Generalise first and specify the result, or scope them to different targets." },

    { "id": "elab-before-thinking", "kind": "order", "first": "ELAB", "then": "@thinking",
      "severity": "note", "label": "order",
      "why": "a topic and its elaboration do not justify each other when the thinking op comes first",
      "suggest": "elab + thinking — elaborate, then operate on what was elaborated." },

    { "id": "brst-needs-frame", "kind": "precondition", "target": "BRST",
      "requiresBefore": ["@subject", "@condition", "@thinking"],
      "severity": "ask", "label": "precondition",
      "why": "ideation is unpredictable without a frame in front of it",
      "suggest": "subject + brst — at minimum a context, condition or thinking op before the brainstorm." },

    { "id": "hyp-needs-subject", "kind": "precondition", "target": "HYP",
      "requiresBefore": ["@subject"],
      "severity": "ask", "label": "precondition",
      "why": "a hypothesis with no stated subject cannot be tested",
      "suggest": "subject + hyp" },

    { "id": "assm-needs-subject", "kind": "precondition", "target": "ASSM",
      "requiresBefore": ["@subject"],
      "severity": "ask", "label": "precondition",
      "why": "an assumption with no stated subject cannot be checked",
      "suggest": "subject + assm" }
  ],

  "notRules": [
    { "pair": "CMP + DIST", "why": "comparing and distinguishing are complementary, not opposed" },
    { "pair": "CRIT + IMPR", "why": "criticise then improve is the natural work sequence" },
    { "pair": "BRST + CAT", "why": "generate items, then group them" },
    { "pair": "ALW + COND", "why": "'always, under this condition' is scoping, not contradiction" },
    { "pair": "POS + CRIT", "why": "criticism can be positive" },
    { "pair": "EXC + INSTOF", "why": "exception and substitution coexist — FUSIONS_WORKSHEET.md, house 7" }
  ]
};
  root.GlyphExpansions = {
  "schema": 2,
  "note": "GENERATED by build-templates.js from expansions.txt (composition) and GLOSSARY.md (definitions) — DO NOT EDIT BY HAND. Every command carries `species` (`atom` = a hieroglyph, does not decompose; `composite` = a glyph, with the `formula` that decomposes it), `depth` (0 for an atom, 1 + the deepest dependency otherwise) and `def`, what the command means. `def` is the only thing an atom has to say about itself.",
  "atoms": 88,
  "composites": 32,
  "maxDepth": 6,
  "commands": {
    "TRUE": {
      "species": "atom",
      "depth": 0,
      "def": "Comparison base: true."
    },
    "FLS": {
      "species": "atom",
      "depth": 0,
      "def": "Comparison base: false."
    },
    "POS": {
      "species": "atom",
      "depth": 0,
      "def": "Positive polarity, assertion or agreement."
    },
    "NGT": {
      "species": "atom",
      "depth": 0,
      "def": "Negative polarity, negation or disagreement."
    },
    "DONT": {
      "species": "atom",
      "depth": 0,
      "def": "Negates doing something: a direct prohibition on an action."
    },
    "DENY": {
      "species": "atom",
      "depth": 0,
      "def": "Rejects what leads to a result: refusal of the route, not of the act itself."
    },
    "PRIO": {
      "species": "atom",
      "depth": 0,
      "def": "Element that takes precedence over others in the context."
    },
    "OVR": {
      "species": "atom",
      "depth": 0,
      "def": "Suspends a prior rule and writes over it."
    },
    "DFN": {
      "species": "atom",
      "depth": 0,
      "def": "Establishes a definition, creates a semantic binding, introduces new concepts."
    },
    "CMP": {
      "species": "atom",
      "depth": 0,
      "def": "Evaluates the relation between values in the context."
    },
    "CNST": {
      "species": "atom",
      "depth": 0,
      "def": "A testable rule, used as the target of a comparison."
    },
    "ASK": {
      "species": "atom",
      "depth": 0,
      "def": "The act of requesting an answer from someone; raises a question."
    },
    "ELAB": {
      "species": "atom",
      "depth": 0,
      "def": "Expands with detail; develops an idea."
    },
    "CLAR": {
      "species": "atom",
      "depth": 0,
      "def": "Makes clear; removes ambiguity."
    },
    "COND": {
      "species": "atom",
      "depth": 0,
      "def": "Logical gate for conditional execution."
    },
    "FMT": {
      "species": "atom",
      "depth": 0,
      "def": "Specifies output shape; presentation pattern."
    },
    "ITR": {
      "species": "atom",
      "depth": 0,
      "def": "Controlled repetition of a process."
    },
    "CONF": {
      "species": "atom",
      "depth": 0,
      "def": "Validates a decision already taken."
    },
    "UNLS": {
      "species": "atom",
      "depth": 0,
      "def": "Negated conditional; excludes execution under a given condition."
    },
    "ONLYIF": {
      "species": "atom",
      "depth": 0,
      "def": "Necessary condition for execution."
    },
    "ONLYW": {
      "species": "atom",
      "depth": 0,
      "def": "Temporal restriction on execution."
    },
    "INSTOF": {
      "species": "atom",
      "depth": 0,
      "def": "Substitution of one action for another."
    },
    "AVD": {
      "species": "atom",
      "depth": 0,
      "def": "Recommendation to steer clear where possible (weak degree)."
    },
    "RDY": {
      "species": "atom",
      "depth": 0,
      "def": "State of being ready to execute."
    },
    "INS": {
      "species": "atom",
      "depth": 0,
      "def": "Direct command to execute."
    },
    "WARN": {
      "species": "atom",
      "depth": 0,
      "def": "Flags a relevant condition without blocking execution."
    },
    "BYP": {
      "species": "atom",
      "depth": 0,
      "def": "Goes around a step without executing it."
    },
    "FIND": {
      "species": "atom",
      "depth": 0,
      "def": "Looks a value up in the context and sets it as target or context object."
    },
    "GT": {
      "species": "atom",
      "depth": 0,
      "def": "Numeric comparison: greater than."
    },
    "GTE": {
      "species": "atom",
      "depth": 0,
      "def": "Greater or equal than. Numeric comparison: greater or equal."
    },
    "LT": {
      "species": "atom",
      "depth": 0,
      "def": "Numeric comparison: less than."
    },
    "LTE": {
      "species": "atom",
      "depth": 0,
      "def": "Lesser or equal than. Numeric comparison: less or equal."
    },
    "EQ": {
      "species": "atom",
      "depth": 0,
      "def": "Equality comparison."
    },
    "NEQ": {
      "species": "atom",
      "depth": 0,
      "def": "Inequality comparison."
    },
    "GET": {
      "species": "atom",
      "depth": 0,
      "def": "Reads a value from the context and holds it until the next interaction."
    },
    "SUB": {
      "species": "atom",
      "depth": 0,
      "def": "Removes an explicit value from the context."
    },
    "ADD": {
      "species": "atom",
      "depth": 0,
      "def": "Adds a value to the context, respecting its type."
    },
    "SWITCH": {
      "species": "atom",
      "depth": 0,
      "def": "Alternation between states by conditional selection."
    },
    "GO": {
      "species": "atom",
      "depth": 0,
      "def": "Executes; proceeds with the pending action."
    },
    "ERROR": {
      "species": "atom",
      "depth": 0,
      "def": "Marks or signals a failure or exception."
    },
    "MAND": {
      "species": "atom",
      "depth": 0,
      "def": "Required, not optional."
    },
    "OPT": {
      "species": "atom",
      "depth": 0,
      "def": "Optional element, may be omitted."
    },
    "ALW": {
      "species": "atom",
      "depth": 0,
      "def": "Permanent behaviour, no exceptions."
    },
    "NEV": {
      "species": "atom",
      "depth": 0,
      "def": "Permanence modifier applied to another rule (e.g. NEV DONT X = never do X)."
    },
    "PT": {
      "species": "atom",
      "depth": 0,
      "def": "Membership relation of an object within a context."
    },
    "VAR": {
      "species": "atom",
      "depth": 0,
      "def": "Mutable element, ready to be defined or reused."
    },
    "PARAM": {
      "species": "atom",
      "depth": 0,
      "def": "Configurable input to a command."
    },
    "PH": {
      "species": "atom",
      "depth": 0,
      "def": "A reserved position in an object, awaiting a value."
    },
    "DEF": {
      "species": "atom",
      "depth": 0,
      "def": "Default value, base behaviour."
    },
    "TPL": {
      "species": "atom",
      "depth": 0,
      "def": "Named mould, defined with [--name= and invoked with [--name."
    },
    "CORE": {
      "species": "atom",
      "depth": 0,
      "def": "Structural foundation of a context object."
    },
    "CTX": {
      "species": "atom",
      "depth": 0,
      "def": "Declared scope."
    },
    "TGT": {
      "species": "atom",
      "depth": 0,
      "def": "Aim, destination or objective."
    },
    "SPEC": {
      "species": "atom",
      "depth": 0,
      "def": "Detailed technical description of a requirement."
    },
    "LOGIC": {
      "species": "atom",
      "depth": 0,
      "def": "Block of mathematical or boolean operations."
    },
    "WHR": {
      "species": "atom",
      "depth": 0,
      "def": "Place marker; spatial context of reference."
    },
    "HGH": {
      "species": "atom",
      "depth": 0,
      "def": "High intensity; raised priority."
    },
    "LOW": {
      "species": "atom",
      "depth": 0,
      "def": "Low intensity; reduced priority."
    },
    "BOLD": {
      "species": "atom",
      "depth": 0,
      "def": "Strong emphasis; prominence in the output."
    },
    "LIGHT": {
      "species": "atom",
      "depth": 0,
      "def": "Soft emphasis; reduced tone in the output."
    },
    "ATC": {
      "species": "atom",
      "depth": 0,
      "def": "Attaches auxiliary context or reference to a command."
    },
    "EX": {
      "species": "atom",
      "depth": 0,
      "def": "The example itself — the datum, the concrete case."
    },
    "RWK": {
      "species": "atom",
      "depth": 0,
      "def": "Rebuilds the structure while keeping the original intent."
    },
    "IMPR": {
      "species": "atom",
      "depth": 0,
      "def": "Raises quality without changing the structure (incremental polish)."
    },
    "REV": {
      "species": "atom",
      "depth": 0,
      "def": "A reading sweep looking for error or inconsistency, with no formal comparison."
    },
    "SKEP": {
      "species": "atom",
      "depth": 0,
      "def": "Takes a sceptical stance towards a proposition."
    },
    "DIST": {
      "species": "atom",
      "depth": 0,
      "def": "Marks the difference between two elements."
    },
    "REAL": {
      "species": "atom",
      "depth": 0,
      "def": "The practical quality standard EVAL measures against."
    },
    "REF": {
      "species": "atom",
      "depth": 0,
      "def": "Points at an external source."
    },
    "SEEAL": {
      "species": "atom",
      "depth": 0,
      "def": "Suggests a relation to another element."
    },
    "NT": {
      "species": "atom",
      "depth": 0,
      "def": "Annotation; marks a relevant point."
    },
    "EXC": {
      "species": "atom",
      "depth": 0,
      "def": "Explicit departure from the general rule."
    },
    "LIM": {
      "species": "atom",
      "depth": 0,
      "def": "Observation that a limit exists (not an imposition)."
    },
    "REQ": {
      "species": "atom",
      "depth": 0,
      "def": "Positive demand — what has to exist."
    },
    "EXT": {
      "species": "atom",
      "depth": 0,
      "def": "Marks an element outside the document's scope."
    },
    "RSN": {
      "species": "atom",
      "depth": 0,
      "def": "The motive underlying a decision."
    },
    "FIN": {
      "species": "atom",
      "depth": 0,
      "def": "Closing or termination marker."
    },
    "IF": {
      "species": "atom",
      "depth": 0,
      "def": "Logical conditional; execution gate."
    },
    "SECTION": {
      "species": "atom",
      "depth": 0,
      "def": "Named structural division grouping related commands."
    },
    "BLOCK": {
      "species": "atom",
      "depth": 0,
      "def": "Atomic unit of execution; groups commands read as a single step."
    },
    "SKL": {
      "species": "atom",
      "depth": 0,
      "def": "Marks an installed skill, invocable inside the Glyph document."
    },
    "NONE": {
      "species": "atom",
      "depth": 0,
      "def": "Absence of value; the empty return of engine operations."
    },
    "TOBLOCK": {
      "species": "atom",
      "depth": 0,
      "def": "Converts a section or a loose set of commands into a BLOCK."
    },
    "TOSECTION": {
      "species": "atom",
      "depth": 0,
      "def": "Converts a block or a loose set of commands into a SECTION."
    },
    "HMN": {
      "species": "atom",
      "depth": 0,
      "def": "Represents the user as a referenceable object."
    },
    "QUICK": {
      "species": "atom",
      "depth": 0,
      "def": "Condensed execution directive: expands an abbreviated command into a full canonical instruction."
    },
    "OFF": {
      "species": "atom",
      "depth": 0,
      "def": "Disables Glyph interpretation from this point on."
    },
    "ON": {
      "species": "atom",
      "depth": 0,
      "def": "Re-enables Glyph interpretation after an OFF."
    },
    "VRFY": {
      "species": "composite",
      "formula": "[CMP-TRUE[[CORE],[TGT]]]",
      "deps": [
        "CMP",
        "TRUE",
        "CORE",
        "TGT"
      ],
      "depth": 1,
      "def": "Compare against truth or fact."
    },
    "VAL": {
      "species": "composite",
      "formula": "[CMP-CTX[CNST]][SUB[EQ[CMP-CTX]]][CAT-EQ]",
      "deps": [
        "CMP",
        "CTX",
        "CNST",
        "SUB",
        "EQ",
        "CMP",
        "CTX",
        "CAT",
        "EQ"
      ],
      "depth": 5,
      "def": "Compare against the constraint or rule."
    },
    "CRIT": {
      "species": "composite",
      "formula": "[CMP[CTX],[SPEC-CORE],[EVAL[ERROR]]]",
      "deps": [
        "CMP",
        "CTX",
        "SPEC",
        "CORE",
        "EVAL",
        "ERROR"
      ],
      "depth": 2,
      "def": "Compare against the declared context or objective."
    },
    "EVAL": {
      "species": "composite",
      "formula": "[REAL[CORE-CTX[DIST[SKL]]]],[REF[DEF[SPEC-CORE-CTX]]]",
      "deps": [
        "REAL",
        "CORE",
        "CTX",
        "DIST",
        "SKL",
        "REF",
        "DEF",
        "SPEC",
        "CORE",
        "CTX"
      ],
      "depth": 1,
      "def": "Compare against a realistic standard of practical quality."
    },
    "SCRU": {
      "species": "composite",
      "formula": "[DIST-RSN[TRYFR[FIND-REAL][WHR[REAL-EQ[R:[CONF]]]]][CTX-VRFY-RSN],[SUM[ASK[DIST-RSN[TRYFR[REAL]]]]]]",
      "deps": [
        "DIST",
        "RSN",
        "TRYFR",
        "FIND",
        "REAL",
        "WHR",
        "REAL",
        "EQ",
        "CONF",
        "CTX",
        "VRFY",
        "RSN",
        "SUM",
        "ASK",
        "DIST",
        "RSN",
        "TRYFR",
        "REAL"
      ],
      "depth": 5,
      "def": "Examine the context under verification, criticise and question."
    },
    "TRYFR": {
      "species": "composite",
      "formula": "[REV[REF[TGT]]][VRFY[TGT],[TRUE[CNCL[GO-LOGIC]]]]",
      "deps": [
        "REV",
        "REF",
        "TGT",
        "VRFY",
        "TGT",
        "TRUE",
        "CNCL",
        "GO",
        "LOGIC"
      ],
      "depth": 4,
      "def": "Attempt to reach the target with verification."
    },
    "PROB": {
      "species": "composite",
      "formula": "[ERROR[CTX]]",
      "deps": [
        "ERROR",
        "CTX"
      ],
      "depth": 1,
      "def": "An error situated inside a specific context."
    },
    "SIMP": {
      "species": "composite",
      "formula": "[RTNL-SUB],[CTX]",
      "deps": [
        "RTNL",
        "SUB",
        "CTX"
      ],
      "depth": 2,
      "def": "Reduce complexity — cut, do not add."
    },
    "GEN": {
      "species": "composite",
      "formula": "[ELAB],[RWK],[SUB-CTX]",
      "deps": [
        "ELAB",
        "RWK",
        "SUB",
        "CTX"
      ],
      "depth": 1,
      "def": "Categorise instances into a base pattern."
    },
    "SUM": {
      "species": "composite",
      "formula": "[SIMP],[CORE]",
      "deps": [
        "SIMP",
        "CORE"
      ],
      "depth": 3,
      "def": "Simplify while keeping the essential foundation."
    },
    "CAT": {
      "species": "composite",
      "formula": "[SUM],[CORE],[ELAB]",
      "deps": [
        "SUM",
        "CORE",
        "ELAB"
      ],
      "depth": 4,
      "def": "Organise into classes."
    },
    "QST": {
      "species": "composite",
      "formula": "[CTX[GET[CORE],[WHR[LOGIC-NONE]]],[ASK]]",
      "deps": [
        "CTX",
        "GET",
        "CORE",
        "WHR",
        "LOGIC",
        "NONE",
        "ASK"
      ],
      "depth": 1,
      "def": "Structural typing: marks a block as interrogative (not necessarily aimed at anyone — see ASK)."
    },
    "DRVF": {
      "species": "composite",
      "formula": "[RTNL-RWK[MAND-NEQ],[CTX[GO-SWITCH]]]",
      "deps": [
        "RTNL",
        "RWK",
        "MAND",
        "NEQ",
        "CTX",
        "GO",
        "SWITCH"
      ],
      "depth": 2,
      "def": "Draw a conclusion from a principle."
    },
    "FOREX": {
      "species": "composite",
      "formula": "[GO-ALT[AVD[GET[CTX-REQ],[CTX-CNST],[CTX-EXC]]]]",
      "deps": [
        "GO",
        "ALT",
        "AVD",
        "GET",
        "CTX",
        "REQ",
        "CTX",
        "CNST",
        "CTX",
        "EXC"
      ],
      "depth": 2,
      "def": "The discourse connective that introduces an EX in the flow of text."
    },
    "FBK": {
      "species": "composite",
      "formula": "[IF-ERROR][EQ[RMBR[CORE]],[INSTOF[TRYFR],[GO[ALT]]]]",
      "deps": [
        "IF",
        "ERROR",
        "EQ",
        "RMBR",
        "CORE",
        "INSTOF",
        "TRYFR",
        "GO",
        "ALT"
      ],
      "depth": 5,
      "def": "Alternative plan of action on failure."
    },
    "RESTR": {
      "species": "composite",
      "formula": "[IF[SKEP[CNST]][TRUE][LIM-GO[CTX-EQ[CNST]]]]",
      "deps": [
        "IF",
        "SKEP",
        "CNST",
        "TRUE",
        "LIM",
        "GO",
        "CTX",
        "EQ",
        "CNST"
      ],
      "depth": 1,
      "def": "The act of limiting the scope of application."
    },
    "DEPR": {
      "species": "composite",
      "formula": "[AVD[GO]],[OPT[REF[INSTOF]]]",
      "deps": [
        "AVD",
        "GO",
        "OPT",
        "REF",
        "INSTOF"
      ],
      "depth": 1,
      "def": "Avoid executing; a replacement may exist."
    },
    "HYP": {
      "species": "composite",
      "formula": "[RMBR[FBK]][IMAG[ONLYIF[CNST-REAL]][TRUE],[ADD[CTX][FOREX-CORE]],[FBK]]",
      "deps": [
        "RMBR",
        "FBK",
        "IMAG",
        "ONLYIF",
        "CNST",
        "REAL",
        "TRUE",
        "ADD",
        "CTX",
        "FOREX",
        "CORE",
        "FBK"
      ],
      "depth": 6,
      "def": "A testable, unconfirmed proposition."
    },
    "IMAG": {
      "species": "composite",
      "formula": "[ADD[CTX[NEQ[REAL]]]]",
      "deps": [
        "ADD",
        "CTX",
        "NEQ",
        "REAL"
      ],
      "depth": 1,
      "def": "Adds a non-real context."
    },
    "ALT": {
      "species": "composite",
      "formula": "[NEQ[CORE]],[EQ[TGT]]",
      "deps": [
        "NEQ",
        "CORE",
        "EQ",
        "TGT"
      ],
      "depth": 1,
      "def": "Differs in means, agrees in end."
    },
    "ASSM": {
      "species": "composite",
      "formula": "[ADD[CORE]],[NEV[VRFY]]",
      "deps": [
        "ADD",
        "CORE",
        "NEV",
        "VRFY"
      ],
      "depth": 2,
      "def": "Enters as foundation, never verified."
    },
    "RTNL": {
      "species": "composite",
      "formula": "[ELAB[RSN]],[REF[CNST]]",
      "deps": [
        "ELAB",
        "RSN",
        "REF",
        "CNST"
      ],
      "depth": 1,
      "def": "A reason elaborated and tied to a criterion."
    },
    "BRST": {
      "species": "composite",
      "formula": "[ITR[ADD[ALT-IMAG]]],[NEV[CNST]]",
      "deps": [
        "ITR",
        "ADD",
        "ALT",
        "IMAG",
        "NEV",
        "CNST"
      ],
      "depth": 2,
      "def": "Iterates imagined alternatives, unconstrained."
    },
    "CNSD": {
      "species": "composite",
      "formula": "[ITR[CMP[ALT],[CNST]]],[NEV[CNCL]]",
      "deps": [
        "ITR",
        "CMP",
        "ALT",
        "CNST",
        "NEV",
        "CNCL"
      ],
      "depth": 4,
      "def": "Weighs each alternative against the rule without concluding."
    },
    "PROP": {
      "species": "composite",
      "formula": "[GO[ALT[RTNL]]],[ASK[CONF]]",
      "deps": [
        "GO",
        "ALT",
        "RTNL",
        "ASK",
        "CONF"
      ],
      "depth": 2,
      "def": "Puts forward an alternative with its rationale and asks for assent."
    },
    "CTRD": {
      "species": "composite",
      "formula": "[NGT[TGT]],[RTNL[DIST]]",
      "deps": [
        "NGT",
        "TGT",
        "RTNL",
        "DIST"
      ],
      "depth": 2,
      "def": "Negates the target and supports it with the difference."
    },
    "CNCL": {
      "species": "composite",
      "formula": "[FIN[DRVF[CORE-CTX]]]",
      "deps": [
        "FIN",
        "DRVF",
        "CORE",
        "CTX"
      ],
      "depth": 3,
      "def": "Final derivation from the context's foundation."
    },
    "JUST": {
      "species": "composite",
      "formula": "[GO[RTNL]],[TGT[CNCL]]",
      "deps": [
        "GO",
        "RTNL",
        "TGT",
        "CNCL"
      ],
      "depth": 4,
      "def": "Deploys the rationale in favour of a conclusion."
    },
    "INTN": {
      "species": "composite",
      "formula": "[DFN[TGT[RSN]]]",
      "deps": [
        "DFN",
        "TGT",
        "RSN"
      ],
      "depth": 1,
      "def": "Declares the target together with its motive."
    },
    "RMBR": {
      "species": "composite",
      "formula": "[ALW[GET[CTX]]]",
      "deps": [
        "ALW",
        "GET",
        "CTX"
      ],
      "depth": 1,
      "def": "Permanent retrieval from the context."
    },
    "FRGT": {
      "species": "composite",
      "formula": "[NEV[GET[CTX]]]",
      "deps": [
        "NEV",
        "GET",
        "CTX"
      ],
      "depth": 1,
      "def": "Never retrieved from the context again."
    },
    "LRN": {
      "species": "composite",
      "formula": "[GEN[RMBR]],[ADD[CORE]]",
      "deps": [
        "GEN",
        "RMBR",
        "ADD",
        "CORE"
      ],
      "depth": 2,
      "def": "Generalises what was retained and folds it into the foundation."
    }
  }
};
  root.GlyphTargets = {
  "schema": 1,
  "note": "Where the engine's output is meant to land. Data, not code: model ids and harness surfaces change on someone else's schedule, so they are declared here instead of compiled into the engine. `available:false` lists a harness that is known but not wired yet — a listed-and-off harness informs, an invented one lies. The UI reads this to show the Regent, before anything is emitted, which file will be written and with what header.",

  "harnesses": [
    {
      "id": "claude-code",
      "label": "Claude Code",
      "available": true,
      "writes": ".claude/agents/<role>.md",
      "registers": "frontmatter `tools:` — a fixed discovery path, not a convention",
      "models": [
        { "id": "inherit", "label": "herda da sessão", "note": "no model: line" },
        { "id": "opus",    "label": "Opus 5",     "full": "claude-opus-5" },
        { "id": "sonnet",  "label": "Sonnet 5",   "full": "claude-sonnet-5" },
        { "id": "haiku",   "label": "Haiku 4.5",  "full": "claude-haiku-4-5-20251001" },
        { "id": "fable",   "label": "Fable 5",    "full": "claude-fable-5" }
      ]
    },
    {
      "id": "anthropic-api",
      "label": "API Anthropic",
      "available": false,
      "writes": "—",
      "registers": "the `tools` parameter of the Messages API",
      "models": []
    },
    {
      "id": "orbital",
      "label": "Runtime _ORBITAL",
      "available": false,
      "writes": "—",
      "registers": "to be defined with the runtime",
      "models": []
    }
  ],

  "roles": [
    { "id": "dv", "label": "DV — implements" },
    { "id": "qa", "label": "QA — risk opinion" },
    { "id": "po", "label": "PO — accepts" },
    { "id": "da", "label": "DA — instruments" },
    { "id": "custom", "label": "outro / avulso" }
  ]
};
})(typeof self !== "undefined" ? self : this);
