/* GENERATED by build-skill.js from scripts/core/emit-xml.js at engine 3.5.8.06 — DO NOT EDIT BY HAND.
   Edit the source in the glyph repository and run: node scripts/build-skill.js */
/**
 * core/emit-xml.js — the glyph-package: the message that travels to the machine.
 *
 * buildXml walks the tree into lines; packagePass is the structural pass that
 * turns those lines into the document PACKAGE_TARGET.md specifies (<holds>,
 * <needs>, chains, bindings); toXML is the one call the CLI and the app make.
 * Reads the tree from parser.js and never writes it — a projection, like the
 * other two. Everything it says about a command comes from the stores
 * (species, depth, formula, def) so `describe` carries the glossary's meaning
 * rather than a paraphrase.
 */

import { xesc, pad, walk, valueChildren } from "./util.js";
import { FRAMES, SLOTS, elName, GLOSS_REVERSE } from "./vocabulary.js";
import { speciesOf, depthOf, formulaOf, defOf, atomsOf, standsAlone } from "./stores.js";
import { parse, collectBindings, bindingOf } from "./parser.js";
import { VERSION } from "./version.js";

/* ======================================================
   5. XML EMITTER — the message that travels to the machine
   ====================================================== */

/* Ceilinged indent. Without the ceiling the XML grows with the SQUARE of
   depth: 500 levels turned into ~500 KB of whitespace, and the XML is
   exactly the thing that gets copied into the chat. Past the ceiling the
   structure stays readable through the tags themselves. */
export function buildXml(segments, opts) {
  if (!segments.length) return "<!-- escolha um molde ou escreva do lado esquerdo -->";
  /* one pass over the whole document, because the scope IS the whole
     document: a reference resolves to a binding written later as readily
     as to one written earlier */
  var o2 = {}, ok2;
  for (ok2 in (opts || {})) if (Object.prototype.hasOwnProperty.call(opts, ok2)) o2[ok2] = opts[ok2];
  o2.__binds = collectBindings(segments, null);
  opts = o2;
  var L = ["<glyph-package engine=\"" + VERSION + "\">", pad(1) + "<schema/>"];
  segments.forEach(function (sg) {
    if (sg.isReturn) {
      var exp = [], bad = [];
      collect(sg.children, exp, bad);
      L.push(pad(1) + "<block" + blockAttrs(sg) + ">");
      var head = '<user-expectative expects="' + xesc(exp.join(",")) + '"';
      /* `expects` is only the flattened summary. Through v1.0.9 it was ALL the
         return block emitted, so literals and nesting were discarded:
         `r-[tgt\`user command blocks\`` lost the whole text. The real body
         travels along with it now. */
      if (!sg.children.length) L.push(pad(2) + head + "/>");
      else {
        L.push(pad(2) + head + ">");
        // emit() already renders an unknown tier as <unresolved>, so `bad`
        // only serves to decide the summary — nothing gets emitted twice.
        sg.children.forEach(function (nd) { emit(nd, 3, L, opts); });
        L.push(pad(2) + "</user-expectative>");
      }
      L.push(pad(1) + "</block>");
      if (sg.breaks) L.push(pad(1) + "<break/>");
      return;
    }
    L.push(pad(1) + "<block" + blockAttrs(sg) + ">");
    if (sg.mood.length) {
      var a = ['dominant="' + xesc(sg.mood[0].gloss) + '"'];
      if (sg.mood.length > 1)
        a.push('also="' + xesc(sg.mood.slice(1).map(function (m) { return m.gloss; }).join(",")) + '"');
      L.push(pad(2) + "<mood " + a.join(" ") + "/>");
    }
    sg.children.forEach(function (nd) { emit(nd, 2, L, opts); });
    L.push(pad(1) + "</block>");
    if (sg.breaks) L.push(pad(1) + "<break/>");
  });
  L.push("</glyph-package>");
  return packagePass(L, opts).join("\n");
}


/* ---- glyph-package, the structural pass (E3b) ------------------------
   Sections 3 and 4 of PACKAGE_TARGET.md are shape, not content, so they run
   as one pass over the emitted lines rather than threading through `emit`.
   The same algorithm was validated against the hand-derived golden byte for
   byte BEFORE any emitter existed, which is the direction lock T5 demands.  */
export function packageIndent(s) { return s.length - s.replace(/^ +/, "").length; }

/* The last line of the element that opens at L[i]: itself when the tag is
   self-closing, otherwise its matching close at the same indent. Used by the
   <holds> pass, which groups elements rather than lines. */
export function packageSpan(L, i) {
  var t = L[i].replace(/^ +/, "");
  if (t.charAt(0) !== "<" || t.indexOf("</") === 0 || /\/>\s*$/.test(t)) return i;
  var m = t.match(/^<([a-z-]+)/);
  if (!m) return i;
  var close = "</" + m[1] + ">", ind = packageIndent(L[i]);
  for (var j = i + 1; j < L.length; j++) {
    var ji = packageIndent(L[j]);
    if (ji < ind) return i;                                   /* left the element unclosed */
    if (ji === ind && L[j].replace(/^ +/, "") === close) return j;
  }
  return i;
}

export function packagePass(L, opts) {
  /* 3 — a maximal run of siblings, first `extend` then `item`s, is one
     <chain>, and the attribute does not survive it: position carries it.
     A second `extend` opens a NEW run (3.4), which is what keeps `-`
     distinguishable from `,`. */
  var out = [];
  for (var i = 0; i < L.length; i++) {
    var line = L[i];
    if (!/\schain="extend"\s*\/>/.test(line)) { out.push(line); continue; }
    var ind = packageIndent(line), run = [line], j = i + 1;
    while (j < L.length && packageIndent(L[j]) === ind && /\schain="item"\s*\/>/.test(L[j])) {
      run.push(L[j]); j++;
    }
    var padding = new Array(ind + 1).join(" ");
    out.push(padding + "<chain>");
    for (var r = 0; r < run.length; r++)
      out.push("  " + run[r].replace(/\schain="(extend|item)"/, ""));
    out.push(padding + "</chain>");
    i = j - 1;
  }

  /* 3b — the same rule for `,` between BRACKETED siblings: a maximal run of
     a head plus its `join="item"` followers is one <holds>, and the attribute
     does not survive it because position carries the operator.

     It cannot reuse the loop above. A chain link is always a bare,
     self-closing line, so a run there is a run of LINES. A conjunction member
     is a bracketed element and spans from its open tag to its close, so this
     one groups SPANS. Same rule, different unit. */
  var held = [];
  for (var h = 0; h < out.length; h++) {
    var headStart = h, headEnd = packageSpan(out, h);
    var hInd = packageIndent(out[h]);
    /* only an element can head a run, and only a following sibling at the
       same indent carrying join="item" can continue it */
    var members = [], k = headEnd + 1;
    while (k < out.length && packageIndent(out[k]) === hInd && /\sjoin="item"[\s/>]/.test(out[k])) {
      var mEnd = packageSpan(out, k);
      members.push([k, mEnd]);
      k = mEnd + 1;
    }
    if (!members.length) { held.push(out[h]); continue; }
    var hp = new Array(hInd + 1).join(" ");
    held.push(hp + "<holds>");
    for (var q = headStart; q <= headEnd; q++) held.push("  " + out[q]);
    members.forEach(function (span) {
      for (var s = span[0]; s <= span[1]; s++)
        held.push("  " + out[s].replace(/\sjoin="item"/, ""));
    });
    held.push(hp + "</holds>");
    h = members[members.length - 1][1];
  }
  out = held;

  /* 4 — <invoke> is a leaf, first child of the element whose call it
     describes, and only where the command is composite: an atom's reading is
     its own name, and saying so on every element is a tautology with a cost. */
  var withInvokes = [];
  for (var m = 0; m < out.length; m++) {
    var l = out[m], t = l.replace(/^ +/, "");
    withInvokes.push(l);
    if (t.charAt(0) !== "<" || t.indexOf("</") === 0 || /\/>$/.test(t)) continue;
    var nm = (t.match(/^<([a-z-]+)[\s>]/) || [])[1];
    var hit = nm && GLOSS_REVERSE[nm];
    if (!hit || speciesOf(hit.canonical, opts) !== "composite") continue;
    withInvokes.push(new Array(packageIndent(l) + 3).join(" ") +
      '<invoke reads="' + xesc(formulaOf(hit.canonical, opts)) + '" species="composite" depth="' +
      depthOf(hit.canonical, opts) + '"/>');
  }
  return withInvokes;
}


export function blockAttrs(sg) {
  return ' once="true"' + (sg.continues ? ' continues="previous"' : "");
}

export function collect(list, acc, bad) {
  walk(list, function (nd) {
    if (!nd.canonical || nd.slotName) return;
    if (nd.tier === "unknown" || nd.tier === "empty") { if (bad) bad.push(nd); }
    else if (nd.canonical !== "PH") acc.push(elName(nd.canonical, nd.tier, nd.gloss));
  });
}

/* Iterative with an explicit stack. The recursive version overflowed the
   JS call stack around 2000 levels, and in Glyph depth grows with the
   query's size (every `[` without a `]` nests). A frame with `tail` holds
   the lines that close the node, pushed before the children so they come
   out after them. */
export function emit(root, startDepth, L, opts) {
  var stack = [{ nd:root, d:startDepth }];

  function pushKids(kids, d) {
    for (var i = kids.length - 1; i >= 0; i--) stack.push({ nd:kids[i], d:d });
  }

  while (stack.length) {
    var f = stack.pop();
    if (f.tail) { for (var t = 0; t < f.tail.length; t++) L.push(f.tail[t]); continue; }

    var nd = f.nd, d = f.d;

    if (nd.literal) {
      if (nd.form === "raw") { L.push(pad(d) + "<off>" + xesc(nd.v.trim()) + "</off>"); continue; }
      // value bound to a template slot: the slot's name travels along with it
      var slotAt = nd.boundSlot ? ' slot="' + xesc(nd.boundSlot) + '"' : "";
      var roleAt = nd.role === "result" ? ' role="result"' : "";
      /* A literal whose text IS a bound name is a reference to it. This is a
         table lookup, not an inference: the name exists because some command
         in this document bound it. The binding literal itself is excluded —
         it declares the name rather than referring to it. */
      var refAt = "";
      if (opts && opts.__binds && !nd.isBinder) {
        var refName = String(nd.v == null ? "" : nd.v).trim();
        if (refName && opts.__binds[refName]) refAt = ' ref="' + xesc(refName) + '"';
      }

      L.push(pad(d) + "<user-input" + slotAt + roleAt + refAt + ">" + xesc(nd.v) + "</user-input>");
      continue;
    }
    if (nd.text) { L.push(pad(d) + "<off>" + xesc(nd.v) + "</off>"); continue; }
    if (nd.mode) { pushKids(nd.children || [], d); continue; }
    /* verbatim: the body is text, and the element carries no children */
    if (nd.rawFence) { L.push(pad(d) + "<raw>" + xesc(nd.v || "") + "</raw>"); continue; }
    if (nd.logic) { emitLogic(nd.logic, d, L); continue; }

    if (nd.template) {
      var ta = ' name="' + xesc(nd.template) + '"' + (nd.isDef ? ' define="true"' : "") +
               (nd.expanded ? ' expanded="true"' : "") +
               (nd.expanded && nd.gloss ? ' means="' + xesc(nd.gloss) + '"' : "");
      var tkids = nd.children || [];
      if (!tkids.length) { L.push(pad(d) + "<template" + ta + "/>"); continue; }
      L.push(pad(d) + "<template" + ta + ">");
      stack.push({ tail:[pad(d) + "</template>"] });
      pushKids(tkids, d + 1);
      continue;
    }

    // empty template slot: the question travels in place of the answer
    if (nd.canonical === "PH") {
      var nameNode = (nd.children || []).filter(function (c) { return c.slotName; })[0];
      var qNode = (nd.children || []).filter(function (c) { return c.literal; })[0];
      L.push(pad(d) + "<needs" + (nameNode ? ' slot="' + xesc(nameNode.raw) + '"' : "") + ">" +
        xesc(qNode ? qNode.v : "sem resposta") + "</needs>");
      continue;
    }

    var open, closeName;
    /* `chain` records the operator that attached a BARE element, and only a
       bare one. A bracketed child already announces its own scope, so marking
       it too would force fromXML() to decide whether chain="extend" meant
       `-rwk` or `-[rwk]` — a second bit smuggled into one attribute. `-[`
       normalises to `[` instead, and the attribute means exactly one thing:
       this element was written bare, by this operator. */
    var chainAttr = (nd.chainElement && (nd.origin === "extend" || nd.origin === "item"))
      ? 'chain="' + nd.origin + '"' : null;

    /* `join` is to `,` between BRACKETED siblings what `chain` is to `-` and
       `,` between bare links. It existed nowhere, and the consequence was
       measured: `[simp'X'],[core]` and `[simp'X'][core]` — conjunction and
       sequence, which GLOSSARY §0.1 gives different readings — emitted the
       same bytes. The AST told them apart by `origin` and both derived
       projections threw the difference away.

       Like `chain`, it does not survive packagePass: <holds> groups the run
       and position carries the operator from there. */
    var joinAttr = (!nd.chainElement && nd.origin === "item") ? 'join="item"' : null;

    if (nd.tier === "unknown" || nd.tier === "empty") {
      var at = ['tag="' + xesc(nd.raw || "") + '"'];
      if (nd.suggestion) at.push('nearest="' + xesc(nd.suggestion.name.toLowerCase()) + '"');
      if (chainAttr) at.push(chainAttr);   /* so [in-zzz reads back as a chain link */
      if (joinAttr) at.push(joinAttr);     /* and [a],[zzz] as a conjunction member */
      open = "<unresolved " + at.join(" ");
      closeName = "unresolved";
    } else {
      var el = elName(nd.canonical, nd.tier, nd.gloss);
      var attrs = [];
      if (nd.editorial) attrs.push('force="editorial"');
      if (nd.colon) attrs.push('name="' + xesc(nd.colon) + '"');
      if (chainAttr) attrs.push(chainAttr);
      if (joinAttr) attrs.push(joinAttr);
      /* the name this command's result answers to, from its own operand */
      /* IMPERATIVO -- um primitivo que RECEBEU operando.

         Nao e especie nova: GLOSSARY §0 tem duas especies em dois eixos e
         uma celula vazia por construcao, entao um terceiro valor quebraria a
         legenda. E POSICAO, como `origin` e `role`.

         `[bold]` sozinho e uma marca. `[bold[ctx]]` e um primitivo mandando
         num operando, e ate agora o documento nao dizia isso -- saia com zero
         diagnosticos e nenhuma marca, aceitando em silencio um filho que o
         comando nunca foi declarado a receber.

         A vizinhanca nao basta: `[bold][ctx]` sao dois irmaos e nao ha
         imperativo ali. E a contencao que faz. */
      if (standsAlone(nd.canonical, opts) &&
          (nd.children || []).some(function (c) { return !!c.canonical && !c.chainElement; }))
        attrs.push('imperative="true"');
      var bindName = bindingOf(nd);
      if (bindName) attrs.push('binds="' + xesc(bindName) + '"');
      /* `describe` makes the message carry its own semantics, so whoever
         reads it does not need the Glyph vocabulary loaded to know what
         `<scrutinise>` means. Nothing here is invented: `means` is the gloss
         and `made-of` is the composition table, both already in the engine.

         Off by default — it changes the deliverable, and the plain form is
         the one every doc and every test describes. */
      if (opts && opts.describe) {
        /* A definição do glossário, não o rótulo do INSTR: `means="Review"`
           não acrescentava nada a `<review>`. Cai no rótulo só se a tabela
           de composição não estiver carregada. */
        var mean = defOf(nd.canonical, opts) || nd.gloss;
        if (mean) attrs.push('means="' + xesc(mean) + '"');
        var sp = speciesOf(nd.canonical, opts);
        if (sp === "composite") {
          /* Unique and sorted, not the raw sequence: as a signature of what
             the command IS, `ctx` appearing four times says nothing more
             than it appearing once — and the raw burn of SCRU is 64 items. */
          var seen = {}, uniq = [];
          (atomsOf(nd.canonical, opts) || []).forEach(function (a) {
            if (!seen[a]) { seen[a] = 1; uniq.push(a.toLowerCase()); }
          });
          attrs.push('made-of="' + xesc(uniq.sort().join(" ")) + '"');
        }
      }
      open = "<" + el + (attrs.length ? " " + attrs.join(" ") : "");
      closeName = el;
    }

    var kids = valueChildren(nd);

    /* ordered slots: each empty position travels as <needs slot="n"> */
    var slots = nd.chainElement ? null : SLOTS[nd.canonical];
    var slotNeeds = [];
    if (slots) {
      var got = kids.length + (nd.colon ? 1 : 0);
      for (var k = got; k < slots.length; k++) slotNeeds.push({ pos:k + 1, want:slots[k] });
    }

    var frame = slots ? null : FRAMES[nd.canonical];
    var needs = (frame && !nd.chainElement && kids.length === 0 && !nd.colon) ? frame[0].replace("*", "") : null;
    var allKids = nd.children || [];

    if (!allKids.length && !needs && !slotNeeds.length) { L.push(pad(d) + open + "/>"); continue; }

    L.push(pad(d) + open + ">");
    if (needs) L.push(pad(d + 1) + "<needs>" + xesc(needs) + "</needs>");

    var tail = [];
    slotNeeds.forEach(function (s) {
      tail.push(pad(d + 1) + '<needs slot="' + s.pos + '">' + xesc(s.want) + "</needs>");
    });
    tail.push(pad(d) + "</" + closeName + ">");
    stack.push({ tail:tail });
    pushKids(allKids, d + 1);
  }
}

export function emitLogic(lg, d, L) {
  L.push(pad(d) + "<logic" + (lg.name ? ' name="' + xesc(lg.name) + '"' : "") + ">");
  lg.rules.forEach(function (r) {
    var at = ['kind="' + r.kind + '"'];
    if (r.name) at.push('var="' + xesc(r.name) + '"');
    L.push(pad(d+1) + "<rule " + at.join(" ") + ">");
    L.push(pad(d+2) + "<source>" + xesc(r.source) + "</source>");
    L.push(pad(d+2) + "<reads>" + xesc(r.reads) + "</reads>");
    if (r.then) L.push(pad(d+2) + "<then>" + xesc(r.then) + "</then>");
    if (r.uses && r.uses.length) L.push(pad(d+2) + "<uses>" + xesc(r.uses.join(", ")) + "</uses>");
    L.push(pad(d+1) + "</rule>");
  });
  lg.missing.forEach(function (v) {
    L.push(pad(d+1) + '<needs var="' + xesc(v) + '">usado e nunca definido</needs>');
  });
  L.push(pad(d) + "</logic>");
}

/** human → glyph → XML, in one call. */
export function toXML(src, opts) {
  return buildXml(parse(src, opts).segments, opts);
}
