/* GENERATED by build-skill.js from scripts/core/inverse.js at engine 3.5.8.06 — DO NOT EDIT BY HAND.
   Edit the source in the glyph repository and run: node scripts/build-skill.js */
/**
 * core/inverse.js — XML → Glyph, and GlyphAST → Glyph: the way back.
 *
 * The pipeline was one-way until 1.2.3.00; this is the half that reads the
 * emitted document (or the AST envelope) and answers with the source that
 * would have produced it. It reads the vocabulary backwards through
 * GLOSS_REVERSE and EMO_REVERSE, which is why those maps live in
 * vocabulary.js and not here: the seam graph measured this section reached
 * from the lexer and the emitter for exactly those two names, and a way back
 * that other stages depend on is not a way back. With the maps gone, nothing
 * imports this module but the entry — it is the top of the graph, and the
 * first stage to leave the monolith whole.
 */

import { esc } from "./util.js";
import { SESSION, GLOSS_REVERSE, EMO_REVERSE } from "./vocabulary.js";
import { VERSION } from "./version.js";

/* ======================================================
   8. XML → GLYPH — the inverse

   The pipeline was one-way until here ("human → glyph → xml → machine"),
   so editing the XML meant editing the deliverable and abandoning the
   source. fromXML() reads the emitter's own output back into bracket
   source, and the normal parse/emit path takes over again.

   Three things do NOT come back, and each is pinned by a test in
   test-corpus.js so none of them gets "fixed" silently:

   - `<template name="X">` is written both by [tpl:X'…'] and by [--X…],
     and nothing in the output separates the two. This always rebuilds
     the [--X invocation: a repo-wide grep found no [tpl: in real use.
   - Content appended to an invocation beyond its declared params
     (collectFills' `extra`) carries no slot marker once expanded, so it
     cannot be told from the template's own body.
   - esc()/xesc() leave ' ` [ ] alone and the literal grammar ends on
     exactly those characters, so such text returns through litSafeXml(),
     the same substitution the interface already makes for form fields.
   ====================================================== */
export function xmlUnescape(s) {
  return String(s).replace(/&(#x[0-9a-fA-F]+|#[0-9]+|amp|lt|gt|quot|apos);/g, function (m, e) {
    if (e === "amp") return "&";
    if (e === "lt") return "<";
    if (e === "gt") return ">";
    if (e === "quot") return '"';
    if (e === "apos") return "'";
    var code = e.charAt(1) === "x" ? parseInt(e.slice(2), 16) : parseInt(e.slice(1), 10);
    return isNaN(code) ? m : String.fromCharCode(code);
  });
}

export function xmlTagName(s) { var m = /^\s*([A-Za-z_][\w.:-]*)/.exec(s); return m ? m[1] : ""; }

export function xmlAttrs(raw) {
  var out = {}, m, re = /([A-Za-z_][\w.:-]*)\s*=\s*"([^"]*)"/g;
  while ((m = re.exec(raw))) out[m[1]] = xmlUnescape(m[2]);
  return out;
}

/* Hand-written, like tokenize(), and for the same reason the rest of this
   file is: the CLI and the test suite run on plain Node with no
   dependencies, and DOMParser exists only in the browser. Using it would
   put the inverse behind a wall the tests cannot reach and split the engine
   in two again, which is the divergence v1.0.9 closed. The dialect to read
   is small and self-imposed — buildXml escapes & < > " and writes no
   namespaces, CDATA or DTD — so this stays a reader for that dialect, not
   an XML parser in general. */
export function xmlTokenize(xml) {
  var T = [], i = 0, n = xml.length;
  function pushText(raw) { if (raw && raw.trim()) T.push({ k:"text", v:xmlUnescape(raw) }); }
  while (i < n) {
    var lt = xml.indexOf("<", i);
    if (lt === -1) { pushText(xml.slice(i)); break; }
    if (lt > i) pushText(xml.slice(i, lt));
    if (xml.substr(lt, 4) === "<!--") {
      var ce = xml.indexOf("-->", lt + 4);
      i = ce === -1 ? n : ce + 3;
      continue;
    }
    var gt = xml.indexOf(">", lt);
    if (gt === -1) { T.push({ k:"truncated" }); break; }
    var inner = xml.slice(lt + 1, gt);
    if (inner.charAt(0) === "/") T.push({ k:"close", tag:xmlTagName(inner.slice(1)) });
    else if (inner.charAt(inner.length - 1) === "/") {
      var body = inner.slice(0, -1);
      T.push({ k:"selfclose", tag:xmlTagName(body), attrs:xmlAttrs(body) });
    } else T.push({ k:"open", tag:xmlTagName(inner), attrs:xmlAttrs(inner) });
    i = gt + 1;
  }
  return T;
}

/* Never throws: a hand-edited panel is one of the inputs, so malformed XML
   has to come back as diagnostics the interface can show, the same way
   parse() answers bad Glyph with gaps instead of an exception. */
export function xmlParseTree(xml) {
  var toks = xmlTokenize(xml), diag = [];
  var root = { tag:"#root", attrs:{}, children:[] };
  var stack = [root];
  toks.forEach(function (tk) {
    var top = stack[stack.length - 1];
    if (tk.k === "text") { top.children.push({ tag:"#text", v:tk.v, attrs:{}, children:[] }); return; }
    if (tk.k === "selfclose") { top.children.push({ tag:tk.tag, attrs:tk.attrs, children:[] }); return; }
    if (tk.k === "open") {
      var el = { tag:tk.tag, attrs:tk.attrs, children:[] };
      top.children.push(el); stack.push(el); return;
    }
    if (tk.k === "close") {
      for (var d = stack.length - 1; d > 0; d--) {
        if (stack[d].tag === tk.tag) {
          if (d < stack.length - 1)
            diag.push({ sev:"note", code:"XmlAutoClose",
              msg:"<code>&lt;/" + esc(tk.tag) + "&gt;</code> closed " + (stack.length - 1 - d) +
                  " elemento(s) que seguiam abertos." });
          stack.length = d;
          return;
        }
      }
      diag.push({ sev:"fix", code:"XmlUnmatchedClose",
        msg:"<code>&lt;/" + esc(tk.tag) + "&gt;</code> closes an element that never opened." });
      return;
    }
    if (tk.k === "truncated")
      diag.push({ sev:"fix", code:"XmlTruncated",
        msg:"<code>&lt;</code> with no <code>&gt;</code>: the xml is truncated." });
  });
  if (stack.length > 1)
    diag.push({ sev:"fix", code:"XmlUnclosed",
      msg:"never closed: " + stack.slice(1).map(function (e) {
        return "<code>&lt;" + esc(e.tag) + "&gt;</code>"; }).join(", ") + "." });
  return { root:root, diag:diag };
}

export function xmlChild(el, tag) {
  var kids = el.children || [];
  for (var i = 0; i < kids.length; i++) if (kids[i].tag === tag) return kids[i];
  return null;
}
export function xmlText(el) {
  var s = "";
  (el.children || []).forEach(function (c) { if (c.tag === "#text") s += c.v; });
  return s;
}

/* A literal ends at the next ' ] or newline, so those characters cannot
   travel inside one. esc()/xesc() do not escape them on the way out, which
   is why the trip back needs this: the same substitution glyph-ui.js has
   always made for what a human types into a form field. */
export function litSafeXml(s) {
  return String(s == null ? "" : s)
    .replace(/'/g, "’").replace(/`/g, "’")
    .replace(/\[/g, "(").replace(/\]/g, ")")
    .replace(/\r?\n/g, " ").trim();
}
export function asLiteral(s) { return "'" + litSafeXml(s) + "'"; }

export function xmlKids(el, diag) {
  var out = "";
  /* `chain="item"` is the `,` of a run and cannot be the run's first link:
     `[in,rwk` does not open a chain. The XML panel is hand-editable, so this
     arrives from a human rather than from the emitter, and the choice is
     between repairing it in silence and saying so. It is promoted to `-`
     and reported — the same rule the rest of this work is built on. */
  var firstChain = true;
  (el.children || []).forEach(function (c) {
    if (c.tag === "#text" || c.tag === "mood" || c.tag === "break") { out += fromXmlNode(c, diag); return; }
    var op = c.attrs && c.attrs.chain;
    if (op === "extend" || op === "item") {
      if (firstChain && op === "item") {
        diag.push({ sev:"fix", code:"XmlChainStartsWithItem",
          msg:"the first link of a chain cannot be <code>chain=\"item\"</code> — " +
              "<code>,</code> continua uma cadeia, não a abre. Promovido a <code>-</code>." });
        c = { tag:c.tag, attrs:cloneWithChain(c.attrs, "extend"), children:c.children };
      }
      firstChain = false;
    } else if (c.tag !== "user-input") {
      firstChain = true;   /* a bracketed sibling ends the run */
    }
    out += fromXmlNode(c, diag);
  });
  return out;
}

export function cloneWithChain(attrs, v) {
  var o = {}, k;
  for (k in attrs) if (Object.prototype.hasOwnProperty.call(attrs, k)) o[k] = attrs[k];
  o.chain = v;
  return o;
}

export function fromXmlLogic(el, diag) {
  var lines = [];
  (el.children || []).forEach(function (c) {
    if (c.tag !== "rule") return;
    var srcEl = xmlChild(c, "source");
    if (srcEl) lines.push(xmlText(srcEl));
  });
  /* <source> is the authored expression, untouched by expandExpr — so the
     block comes back as it was written, not as it was read back to the
     human. <needs var> is regenerated by parseLogic on the next pass. */
  var nm = el.attrs.name ? ":" + litSafeXml(el.attrs.name) : "";
  return "[logic" + nm + "]\n" + lines.join("\n") + "\n[/logic]";
}

export function fromXmlTemplate(el, diag) {
  var nm = el.attrs.name || "";
  var head = "[--" + nm + (el.attrs.define ? "=" : "");
  if (el.attrs.expanded) {
    /* An expanded invocation holds the template's body, not the call. The
       bound values are the ones carrying a slot, and rebuilding them as
       named [ph-x'v'] fills is exactly what collectFills reads back — so
       the call survives even though the expansion it produced is discarded
       and regenerated. What the caller appended beyond the declared params
       has no slot and cannot be recovered; see the section note. */
    var fills = "";
    (function scan(list) {
      (list || []).forEach(function (c) {
        if (c.tag === "user-input" && c.attrs && c.attrs.slot && /^[A-Za-z]/.test(c.attrs.slot)) {
          fills += "[ph-" + c.attrs.slot + asLiteral(xmlText(c)) + "]";
          return;
        }
        scan(c.children);
      });
    })(el.children);
    return head + fills + "]";
  }
  return head + xmlKids(el, diag) + "]";
}

export function fromXmlNode(el, diag) {
  var tag = el.tag;
  if (tag === "#text") return "";
  if (tag === "user-input") return asLiteral(xmlText(el));
  if (tag === "off") return " " + litSafeXml(xmlText(el)) + " ";
  if (tag === "mood" || tag === "break") return "";   /* handled per block */
  /* the verbatim fence returns verbatim: it is the one element whose
     content must NOT be re-read, because carrying it unread is the whole
     reason it exists */
  if (tag === "raw") return "[raw]" + xmlText(el) + "[/raw]";
  if (tag === "logic") return fromXmlLogic(el, diag);
  if (tag === "template") return fromXmlTemplate(el, diag);
  if (tag === "unresolved") {
    var uop = chainOpOf(el, diag, litSafeXml(el.attrs.tag || ""));
    if (uop) return uop + litSafeXml(el.attrs.tag || "");
    return "[" + litSafeXml(el.attrs.tag || "") + xmlKids(el, diag) + "]";
  }
  if (tag === "needs") {
    /* Three shapes share this element, and one attribute tells them apart:
       a real [ph-name] hole carries an alpha slot, while the FRAMES and
       SLOTS fillers carry none or a bare number. Only the hole is source;
       the fillers are the engine asking a question, and buildXml asks it
       again from the vocabulary on the next pass. Writing them back would
       turn a prompt into an answer. */
    var slot = el.attrs.slot;
    if (slot && /^[A-Za-z]/.test(slot))
      return "[ph-" + slot + "`" + litSafeXml(xmlText(el)) + "`]";
    return "";
  }

  var hit = GLOSS_REVERSE[tag];
  var name = hit ? hit.canonical.toLowerCase() : (SESSION[tag] ? tag : null);
  if (!name) {
    diag.push({ sev:"note", code:"XmlUnknownElement",
      msg:"<code>&lt;" + esc(tag) + "&gt;</code> matches no command — " +
          "o conteúdo foi mantido, a marca não." });
    return xmlKids(el, diag);
  }
  /* A bare link carries no scope, so it rebuilds as the operator plus the
     name — no brackets, no recursion into children. Writing `[name…]` here is
     exactly what fabricated a <needs>: the bracket gave the command a scope
     to want an operand in, and the engine duly asked for one the author had
     never omitted. Writing `-name` instead lets the following <user-input>
     land on the parent, where the author put it.

     It runs after GLOSS_REVERSE, so an alias rebuilds under its canonical
     name like the bracketed path, and it is the only writer of `-` and `,`,
     so a run comes back in source order with no reordering pass. */
  var op = chainOpOf(el, diag, name);
  if (op) return op + name;

  /* `force="editorial"` is not read back: nd.editorial comes from
     EDITORIAL_ONLY keyed by the canonical, so it returns on its own. */
  /* `,` before a BRACKETED sibling — the conjunction operator, put back from
     the position the <holds> run recorded it in. `chainOpOf` above is the
     bare-link writer of `-` and `,`; this is the bracketed one. */
  var lead = el.attrs.join === "item" ? "," : "";
  var head = lead + "[" + name + (el.attrs.name ? ":" + litSafeXml(el.attrs.name) : "");
  return head + xmlKids(el, diag) + "]";
}

/* Shared by the resolved and unresolved branches. Returns "-" or "," for a
   chain link, or null. A chain element with children is malformed — a bare
   tag cannot hold any — so the children are re-attached to the parent, which
   is what the bracket form would have done, and the reader says so rather
   than repairing it quietly. */
export function chainOpOf(el, diag, name) {
  var op = el.attrs && el.attrs.chain;
  if (op !== "extend" && op !== "item") return null;
  var kids = (el.children || []).filter(function (c) { return c.tag !== "#text"; });
  if (kids.length)
    diag.push({ sev:"fix", code:"XmlChainHasChildren",
      msg:"<code>&lt;" + esc(el.tag) + " chain&gt;</code> has children — a link written without " +
          "<code>[</code> não tem escopo para segurá-los. Reanexados ao pai." });
  return op === "item" ? "," : "-";
}


/* ------------------------------------------------------------------ *
 * fromAST — the path the promotion of the AST implies and never had
 *
 * There was no AST-to-source path in this engine at all: fromXML was the
 * only inverse, so reconstructing source meant going through the XML. That
 * was coherent while the XML was the deliverable. Under T23 it is not, and
 * it costs something concrete — `[A],[B]` and `[A][B]` emit IDENTICAL XML,
 * because the chain attribute marks bare links only, so a comma between
 * bracketed commands cannot come back that way. The AST records it as
 * `origin: "item"` and always did.
 *
 * So the fix is not to make the XML carry it — that needs a second attribute
 * and reopens the ambiguity §3.2 closed. It is to read the source of truth
 * directly. The XML→source path stays as a convenience, one-way in the same
 * sense toHGML is, and nothing that matters depends on it any more.
 *
 * Reads the `full` projection only. A `panel` envelope is refused rather
 * than half-read: thinning makes a field's absence mean six different things,
 * and a reconstructor that guesses is worse than one that stops.
 * ------------------------------------------------------------------ */
export function fromAST(env, opts) {
  opts = opts || {};
  var diag = [];
  if (!env || typeof env !== "object" || env.type !== "GlyphAST") {
    diag.push({ sev:"fix", code:"NotAnAST",
      msg:"not a <code>GlyphAST</code> envelope." });
    return { src:"", diag:diag };
  }
  if (env.projection && env.projection !== "full") {
    diag.push({ sev:"fix", code:"ThinnedAST",
      msg:"projection <code>" + esc(String(env.projection)) + "</code> — only the projection " +
          "<code>full</code> pode ser reconstruída. Na projeção de painel a ausência de um " +
          "campo não distingue vazio de descartado." });
    return { src:"", diag:diag };
  }

  function lit(v, form) {
    var t = String(v == null ? "" : v);
    /* the backtick form is preserved when it was used and is still safe;
       otherwise the quote form, escaped the way fromXML escapes it */
    if (form === "tick" && t.indexOf("`") === -1) return "`" + t + "`";
    return asLiteral(t);
  }

  function kids(list) {
    var out = "";
    (list || []).forEach(function (n) { out += node(n); });
    return out;
  }

  function node(n) {
    if (!n || typeof n !== "object") return "";
    switch (n.type) {
      /* `form:"raw"` is unquoted prose, not a literal: quoting it would put
         delimiters into text the author never delimited */
      case "Raw":     return n.form === "raw" ? String(n.value == null ? "" : n.value)
                                              : lit(n.value, n.form);
      case "Literal": return lit(n.value, n.form);
      case "Text":    return String(n.value == null ? "" : n.value);
      case "ModeOff": return "[off]" + kids(n.body) + "[on]";
      case "Template": {
        /* An expanded invocation holds the template's BODY, not the call.
           Writing the body back would replace what the author typed with
           what it expanded to — the same trap fromXmlTemplate avoids. The
           bound values are the ones carrying a slot; everything else is
           regenerated from the store on the next pass. */
        if (n.expanded) {
          var fills = "";
          (function scan(list) {
            (list || []).forEach(function (c) {
              if (c && c.type === "Command" && c.slotName) return;   /* the binder itself */
              /* a BOUND value is the call; an unbound one is the template's
                 own prompt, and writing that back turns a question into an
                 answer — the same rule <needs> follows */
              if (c && (c.type === "Literal" || c.type === "Raw") && c.slot &&
                  /^[A-Za-z]/.test(c.slot)) {
                fills += "[ph-" + c.slot + lit(c.value, c.form) + "]";
                return;
              }
              if (c && c.body) scan(c.body);
            });
          })(n.body);
          return "[--" + String(n.name || "") + fills + "]";
        }
        return "[--" + String(n.name || "") + (n.isDefinition ? "=" : "") + kids(n.body) + "]";
      }
      /* verbatim in, verbatim out: lit() would substitute exactly the
         characters this fence exists to carry. NOT `Raw`, which this AST
         already uses for unquoted prose. */
      case "Verbatim":
        return "[raw]" + String(n.value == null ? "" : n.value) + "[/raw]";
      case "Logic": {
        var lines = (n.rules || []).map(function (r) { return String(r.source || ""); });
        return "[logic" + (n.name ? ":" + n.name : "") + "]\n" + lines.join("\n") + "\n[/logic]";
      }
      case "Truncated":
        diag.push({ sev:"fix", code:"TruncatedAST",
          msg:"the envelope was truncated at depth " + n.atDepth + " and omitted " +
              n.omittedNodes + " nós — não há o que reconstruir a partir dele." });
        return "";
      case "Command": {
        /* `raw` as written: an unresolved tag keeps its case, because
           `<unresolved tag="A">` is what the author typed and lowercasing it
           would make the reconstruction a different unknown command */
        var name = String(n.raw || n.canonical || "");
        /* the placeholder's name is bound by `-`, which is a name binder here
           and not a chain operator — §2.5 is why its origin is suppressed */
        if (n.slotName) return "-" + name;
        /* a bare link carries no scope: the operator plus the name, no
           brackets, exactly as fromXML writes it — writing [name…] here is
           what fabricates a <needs> */
        if (n.chainElement)
          return (n.origin === "item" ? "," : "-") + name;
        var lead = n.origin === "item" ? "," : "";
        return lead + "[" + name + (n.name ? ":" + litSafeXml(n.name) : "") + kids(n.body) + "]";
      }
      default:
        diag.push({ sev:"note", code:"AstUnknownNode",
          msg:"node <code>" + esc(String(n.type)) + "</code> is not in the AST vocabulary — ignored." });
        return "";
    }
  }

  var parts = [];
  (env.segments || []).forEach(function (seg) {
    var pre = "";
    if (seg.mood && seg.mood.length)
      pre += "/" + seg.mood.map(function (m) { return m.name; }).join("/") + "/";
    if (seg.continues) pre += "[=";
    if (seg.isReturn) pre += "r-";
    parts.push(pre + kids(seg.body) + (seg.breaks ? ";;" : ""));
  });
  /* `;;` already closed its segment, so it must not be followed by `;` */
  var src = parts.reduce(function (acc, cur, i) {
    if (i === 0) return cur;
    return acc + (/;;$/.test(acc) ? "" : ";") + cur;
  }, "");

  return { src:src, diag:diag };
}

export function fromXmlBlock(el, diag) {
  var pre = "";
  var mood = xmlChild(el, "mood");
  if (mood) {
    var keys = [];
    [mood.attrs.dominant].concat(String(mood.attrs.also || "").split(","))
      .forEach(function (g) {
        var k = EMO_REVERSE[String(g || "").trim().toLowerCase()];
        if (k) keys.push(k);
      });
    if (keys.length) pre += "/" + keys.join("/") + "/";
  }
  var exp = xmlChild(el, "user-expectative");
  /* `expects` is only the flattened summary of what the body already says,
     so the body is what gets rebuilt — the attribute regenerates from it. */
  if (exp) return pre + "r-" + xmlKids(exp, diag);
  var body = "";
  (el.children || []).forEach(function (c) {
    if (c.tag === "mood" || c.tag === "#text") return;
    body += fromXmlNode(c, diag);
  });
  return pre + body;
}

/** xml → glyph. The inverse of toXML, within the limits noted above. */
/* ---- glyph-package, the inverse of packagePass (E4) ------------------
   The reader is given a document, not an AST, and the shape sections 3 to 5
   added is undone here so every rule below it keeps working unchanged.

   <invoke> is DISCARDED and never read back. It is derived from the store,
   so reconstructing a command from it would be the engine answering its own
   question - which is finding A3, the defect where the inverse INVENTED a
   <needs> the author was never asked for. A loss can be pinned; an invention
   cannot. <schema/> goes the same way: it carries no authored content.  */
export function packageUnpass(el, diag) {
  if (!el || !el.children) return el;
  var out = [];
  el.children.forEach(function (c) {
    if (c.tag === "schema" || c.tag === "invoke") return;
    if (c.tag === "holds") {
      /* the mirror of the <chain> rule one branch down: position carried the
         operator, so position gives it back. The head came with no operator,
         every other member from `,`. */
      var firstHeld = true;
      (c.children || []).forEach(function (m) {
        if (m.tag === "#text") return;
        if (m.attrs && m.attrs.join)
          diag.push({ sev:"fix", code:"XmlHoldsCarriesJoin",
            msg:"a <code>&lt;holds&gt;</code> member carries <code>join=\"" + esc(m.attrs.join) +
                "\"</code>. Dentro de um <code>&lt;holds&gt;</code> a posição já diz o operador — " +
                "remova o atributo." });
        var hm = {}, hk;
        for (hk in m) if (Object.prototype.hasOwnProperty.call(m, hk)) hm[hk] = m[hk];
        if (!firstHeld) {
          var ha = {}, hak;
          for (hak in (m.attrs || {})) if (Object.prototype.hasOwnProperty.call(m.attrs, hak)) ha[hak] = m.attrs[hak];
          ha.join = "item";
          hm.attrs = ha;
        }
        out.push(packageUnpass(hm, diag));
        firstHeld = false;
      });
      return;
    }
    if (c.tag === "chain") {
      /* position carried the operator, so position gives it back:
         the first member came from `-`, every other from `,` (3.2) */
      var first = true;
      (c.children || []).forEach(function (m) {
        if (m.tag === "#text") return;
        /* The panel is hand-editable, so a <chain> can arrive carrying things
           the emitter never writes. Position decides the operator (3.2) and
           overwriting whatever is there would be repairing in silence, which
           is the one thing this reader refuses to do. Both refusals keep the
           names XML_REFERENCE 11.3 documents; only their trigger moved. */
        if (m.attrs && m.attrs.chain)
          diag.push({ sev:"fix", code:"XmlChainStartsWithItem",
            msg:"a <code>&lt;chain&gt;</code> member carries <code>chain=\"" + esc(m.attrs.chain) +
                "\"</code>. Dentro de um <code>&lt;chain&gt;</code> a posição já diz o operador — " +
                "remova o atributo." });
        /* a member with children is caught downstream by the existing
           XmlChainHasChildren check, which sees the `chain` this function
           assigns; raising it here as well would report one fault twice */
        var mm = {}, mk;
        for (mk in m) if (Object.prototype.hasOwnProperty.call(m, mk)) mm[mk] = m[mk];
        mm.attrs = cloneWithChain(m.attrs || {}, first ? "extend" : "item");
        out.push(packageUnpass(mm, diag));
        first = false;
      });
      return;
    }
    out.push(packageUnpass(c, diag));
  });
  /* copy the node whole and swap only its children: a text node carries its
     content in a property this function must not know the name of */
  var copy = {}, k;
  for (k in el) if (Object.prototype.hasOwnProperty.call(el, k)) copy[k] = el[k];
  copy.children = out;
  return copy;
}


export function fromXML(xmlString, opts) {
  opts = opts || {};
  var pt = xmlParseTree(String(xmlString == null ? "" : xmlString));
  var diag = pt.diag.slice();
  var glyphEl = xmlChild(pt.root, "glyph-package");
  if (!glyphEl) {
    /* the retired root is refused BY NAME, never absorbed in silence - the
       same treatment the divide operator and the backslash mood got */
    if (xmlChild(pt.root, "glyph")) {
      diag.push({ sev:"fix", code:"XmlLegacyRoot",
        msg:"<code>&lt;glyph&gt;</code> was replaced by <code>&lt;glyph-package&gt;</code> in this " +
            "version. Re-emit the document with engine " + VERSION + "." });
      return { src:"", diag:diag };
    }
    diag.push({ sev:"fix", code:"NoGlyphRoot",
      msg:"no <code>&lt;glyph-package&gt;</code> at the root — this is not xml from this engine." });
    return { src:"", diag:diag };
  }
  glyphEl = packageUnpass(glyphEl, diag);
  var parts = [];
  (glyphEl.children || []).forEach(function (el) {
    if (el.tag === "#text") return;
    /* <block> is written by two different things: the wrapper buildXml puts
       around every segment, and the STRUCT command [block'…']. They are the
       same element name, and only position plus the `once` attribute
       separate them — the wrapper is always a direct child of <glyph> and
       always carries `once`, because blockAttrs() runs nowhere else. A
       nested [block reaches fromXmlNode instead, through GLOSS_REVERSE. */
    if (el.tag === "block" && el.attrs.once) {
      parts.push({ src:(el.attrs.continues ? "[=" : "") + fromXmlBlock(el, diag), brk:false });
      return;
    }
    if (el.tag === "break") { if (parts.length) parts[parts.length - 1].brk = true; return; }
    diag.push({ sev:"note", code:"XmlUnexpectedTop",
      msg:"<code>&lt;" + esc(el.tag) + "&gt;</code> outside a block — ignored." });
  });
  var src = parts.map(function (p, i) {
    /* `;;` fecha o bloco tanto quanto `;`, entao ele SUBSTITUI o separador
       em vez de se somar a ele. Escrever os dois produzia `[a];;;[b]`. */
    if (i === parts.length - 1) return p.src;
    return p.src + (p.brk ? ";;" : ";");
  }).join("");
  return { src:src, diag:diag };
}
