/* GENERATED by build-skill.js from scripts/core/parser.js at engine 3.5.8.06 — DO NOT EDIT BY HAND.
   Edit the source in the glyph repository and run: node scripts/build-skill.js */
/**
 * core/parser.js — tokens into the tree, and the tree into a fact.
 *
 * parse() is the source of truth's author: the AST every projection reads.
 * It takes the lexer's tokens, nests by `[` and `]`, attaches operators
 * (`origin`: nest, item, extend, root), expands templates, runs the rules and
 * the constraints, and collects the bindings — a command's operand literal
 * NAMES its result, and `ref` resolves against that. The bindings pass lived
 * in the emitter's section and was reached from here; it is a fact about the
 * tree, so it lives with the tree. Every diagnostic is a `G(...)` call and
 * every subordinate pass receives G — parse hands out what it owns, and
 * imports what it reads.
 */

import { LIMITS, esc, walk, stripTags, valueChildren } from "./util.js";
import { INSTR, PTBR, EDITORIAL_ONLY, ALIAS, STRUCT, META, EMO, SESSION, FRAMES, NAMED_STRUCT, SLOTS } from "./vocabulary.js";
import { templateRegistry, expansionRegistry, entryOf } from "./stores.js";
import { tokenize, classify, suggest } from "./lexer.js";
import { parseLogic } from "./logic.js";
import { expandInvocations, checkTemplateConstraints } from "./templates.js";
import { checkRules } from "./rules.js";

/* ======================================================
   4. PARSER
   ====================================================== */
/**
 * parse(input, opts)
 *   input — Glyph source code (string) or an already-tokenized array.
 *   opts  — { session:true, valency:true }
 * Returns { segments, gaps, tokens }.
 */
export function parse(input, opts) {
  opts = opts || {};
  var tokens = typeof input === "string" ? tokenize(input) : input;
  var gaps = [], segments = [], stack = [], uid = 0;
  var seg = newSeg(), pendingOrigin = null;

  function newSeg() { return { children:[], mood:[], autoClosed:0, breaks:0 }; }
  function top() { return stack.length ? stack[stack.length-1] : null; }
  function attach(nd) { var t = top(); if (t) { t.children.push(nd); nd.parent = t; } else seg.children.push(nd); }
  /* Duas línguas por diagnóstico. O rótulo e a mensagem em inglês chegam
     como 5º e 6º argumentos; faltando, fica o pt-BR — um sítio esquecido
     aparece na língua errada, que é melhor que aparecer vazio. */
  function G(sev, lab, msg, code, enLab, enMsg, tk) {
    var en = opts.lang === "en";
    var g = { sev:sev, lab:(en && enLab) || lab, msg:(en && enMsg) || msg, code:code || "Note" };
    /* Additive, and optional. A refusal with no coordinate cannot be located
       by a reader who does not have the engine — which is the whole point of
       carrying the AST between machines. Every token already holds s/e, so
       this costs a field and no plumbing, and the existing consumers read
       { sev, lab, msg } and are unaffected. */
    if (tk && typeof tk.s === "number") g.at = { s:tk.s, e:tk.e };
    gaps.push(g);
  }
  function closeSeg(cause) {
    var names = [];
    while (stack.length) {
      var closing = stack.pop();
      closing.autoClosed = true; seg.autoClosed++;
      if (names.length < 4) names.push(String(closing.canonical || closing.template || "?").toLowerCase());
    }
    if (cause === "semi" && seg.autoClosed > LIMITS.autoClose)
      G("note", "fecha tudo",
        "<code>;</code> fechou " + seg.autoClosed + " comandos de uma vez (" +
        names.map(function (x) { return "<code>[" + esc(x) + "</code>"; }).join(", ") +
        "…). Em bloco longo isso costuma fechar mais do que se pretendia — feche com <code>]</code> o que for parcial.", "MassAutoClose",
          "closed everything", "<code>;</code> closed " + seg.autoClosed + " commands at once (" + names.map(function (x) { return "<code>[" + esc(x) + "</code>"; }).join(", ") + "…). In a long block that usually closes more than intended — close what is partial with <code>]</code>.");
    seg.cause = cause;
    if (seg.children.length || seg.mood.length || seg.breaks) segments.push(seg);
    seg = newSeg(); pendingOrigin = null;
  }

  for (var i = 0; i < tokens.length; i++) {
    var tk = tokens[i];

    if (tk.k === "open" || tk.k === "bareTag") {
      var cl = classify(tk.v, opts);
      var parentNode = top();
      var inPH = !!(parentNode && parentNode.canonical === "PH");
      if (tk.k === "open" && !tk.v)
        G("fix", "sem nome", "<code>[</code> sem nome. Um <code>[</code> = um comando.", "EmptyCommandName",
          "no name", "<code>[</code> with no name. One <code>[</code> is one command.");
      /* `[ph-alvo` uses `-` as a name binder, not a chain operator: the bare
         tag becomes the placeholder's name and is consumed by the PH branch
         rather than emitted as an element. Its origin would read "extend",
         which is an artefact of the shared lexer path — so it is suppressed
         and no chain attribute can reach a <needs slot="…">. */
      var isSlotName = inPH && tk.k === "bareTag";
      var nd = {
        id:++uid, raw:tk.v, tier:cl.tier, canonical:cl.canonical, gloss:cl.gloss,
        alias:!!cl.alias, children:[], emotions:[], colon:null, autoClosed:false, tok:tk,
        editorial:!!EDITORIAL_ONLY[cl.canonical],
        /* which operator produced the edge to this node's parent */
        origin: isSlotName ? null
              : (pendingOrigin || (tk.k === "bareTag" ? "extend" : (parentNode ? "nest" : "root"))),
        /* Narrowed to the one question it is actually asked: was this written
           BARE, with no `[` of its own, and therefore cannot hold an operand?
           It used to answer that *and* "which operator attached it", and the
           two are independent — `[in-rwk]` and `[in-[rwk]]` share an origin
           and differ in bareness. Conflating them is why an extend could not
           be recovered from the XML, and why `-[` silently cancelled the
           <needs> a bracketed command asks for. */
        chainElement: tk.k === "bareTag",
        slotName: isSlotName,
        depth: stack.length
      };
      if (cl.tier === "unknown" && !nd.slotName) {
        var sg = suggest(tk.v);
        nd.suggestion = sg;
        G("fix", "não existe",
          "<code>[" + esc(tk.v) + "</code> fora do vocabulário." +
          (sg ? " → <code>[" + sg.name.toLowerCase() + "</code>" +
                (PTBR[sg.name] ? " (" + PTBR[sg.name] + ")" : "") + "?" : " Veja a tabela."), "UnknownCommand",
          "does not exist", "<code>[" + esc(tk.v) + "</code> is outside the vocabulary." + (sg ? " → <code>[" + sg.name.toLowerCase() + "</code>" + (INSTR[sg.name] ? " (" + INSTR[sg.name] + ")" : "") + "?" : " See the table."));
      }
      attach(nd);
      if (tk.k === "open") stack.push(nd);
      pendingOrigin = null;
      continue;
    }

    switch (tk.k) {
      case "rawfence": {
        /* No sub-grammar at all: the body is what the author wrote. */
        attach({ rawFence:true, v:tk.body, children:[], tok:tk, origin: pendingOrigin || "nest" });
        if (!tk.closed) G("fix", "não fechou", "<code>[raw]</code> sem <code>[/raw]</code>.", "UnclosedRaw",
          "not closed", "<code>[raw]</code> without <code>[/raw]</code>.");
        pendingOrigin = null;
        break;
      }
      case "logic": {
        var lg = parseLogic(tk.v, tk.body);
        attach({ logic:lg, children:[], tok:tk, origin: pendingOrigin || "nest" });
        lg.gaps.forEach(function (g) { gaps.push(g); });
        if (!tk.closed) G("fix", "não fechou", "<code>[logic]</code> sem <code>[/logic]</code>.", "UnclosedLogic",
          "not closed", "<code>[logic]</code> without <code>[/logic]</code>.");
        pendingOrigin = null;
        break;
      }
      case "tpl": {
        var tnode = { template:tk.v, isDef:!!tk.def, children:[], tok:tk,
                      origin: pendingOrigin || (top() ? "nest" : "root") };
        attach(tnode); stack.push(tnode); pendingOrigin = null;
        break;
      }
      case "chain": seg.continues = true; break;

      case "close":
        if (!stack.length) G("fix", "sobrando", "<code>]</code> sem comando aberto.", "UnmatchedCloseBracket",
          "spare", "<code>]</code> with no command open.");
        else stack.pop();
        pendingOrigin = null;
        break;

      case "closeTag": {
        var found = -1;
        for (var s2 = stack.length-1; s2 >= 0; s2--)
          if (String(stack[s2].canonical).toUpperCase() === String(tk.v).toUpperCase()) { found = s2; break; }
        if (found === -1) G("fix", "sobrando", "<code>[/" + esc(tk.v) + "]</code> fecha comando não aberto.", "UnmatchedCloseTag",
          "spare", "<code>[/" + esc(tk.v) + "]</code> closes a command that never opened.");
        else stack.length = found;
        break;
      }

      case "colon": {
        var t2 = top();
        if (!t2) break;
        var parts = [], j5 = i + 1, sawComma = false;
        while (j5 < tokens.length) {
          var nx = tokens[j5];
          if (nx.k === "close" || nx.k === "semi" || nx.k === "open" || nx.k === "linebreak" || nx.k === "logic") break;
          if (nx.k === "comma") { sawComma = true; parts.push(","); j5++; continue; }
          if (nx.k === "literal" || nx.k === "text") { parts.push(String(nx.v).trim()); j5++; continue; }
          if (nx.k === "equals") { parts.push("="); j5++; continue; }
          if (nx.k === "extend") { parts.push("-"); j5++; continue; }
          break;
        }
        t2.colon = parts.join(" ").replace(/\s+,/g, ",").trim();
        if (sawComma && !STRUCT[t2.canonical])
          G("ask", "ordem incerta",
            "<code>[" + esc(t2.raw) + ": a,b,c]</code> ordem não inferível. Aninhe.", "AmbiguousSlotOrder",
          "order unclear", "<code>[" + esc(t2.raw) + ": a,b,c]</code> order cannot be inferred. Nest them.");
        i = j5 - 1;
        break;
      }

      case "literal": {
        var t3 = top();
        var lit = { literal:true, v:tk.v, form:tk.form, tok:tk };
        /* The literal's ROLE, decided by position and nothing else.

           `[alw`X`[get[ctx]]]` and `[alw[get[ctx]]`X`]` emitted the same
           <user-input> and differed only by sibling order, so a consumer had
           to INFER "before the nest = operand, after = result" from position.
           That is the inference the Regent ruled out: a variable must arrive
           substituted, not deduced.

           The rule is the Regent's own reading: a literal written before any
           nested command is what the command operates ON; one written after a
           nest has closed names what came BACK. `operand` is the default and
           is not written; `result` is.

           It is derived from position, so the inverse rebuilds it for free
           and it costs the round trip nothing.

           A CHAIN LINK does not count: GLOSSARY §0.1 says `[A-B]` is A and B
           applied to the SAME operand, so the literal after `[rtnl-go`x`]` is
           what both links operate on, not something `go` handed back. Only a
           BRACKETED nest closes and yields. */
        if (t3) lit.role = (t3.children || []).some(function (c) {
          return !!c.canonical && !c.chainElement;
        }) ? "result" : "operand";
        if (t3) t3.children.push(lit); else seg.children.push(lit);
        /* The message used to read "Feche com ``` antes." — advice the author has
           already followed, because the closing backtick IS there, just after
           the `]`. Naming the fix instead of the cause made a one-line lexer
           rule impossible to read out of the diagnostic: the culprit is the
           character itself, and there is no escape for it under either quote. */
        if (tk.closedBy === "bracket" || tk.closedBy === "semi")
          G("fix", "texto cortado",
            "<code>" + (tk.closedBy === "bracket" ? "]" : ";") +
            "</code> encerra o literal aqui, e não há escape para ele. Reescreva o texto sem esse caractere.",
            "TruncatedLiteral",
          "text cut", "<code>" + (tk.closedBy === "bracket" ? "]" : ";") +
            "</code> ends the literal here, and there is no escape for it. Rewrite the text without that character.");
        if (tk.closedBy === "eof") G("fix", "texto aberto", "<code>`</code> sem fechar.", "UnterminatedLiteral",
          "text left open", "<code>`</code> never closed.");
        if (tk.form === "quote" && tk.closedBy === "unterminated")
          G("fix", "texto aberto", "<code>'</code> sem fechar.", "UnterminatedLiteral",
          "text left open", "<code>'</code> never closed.");
        pendingOrigin = null;
        break;
      }

      case "emotion": {
        var key = tk.v.toLowerCase();
        if (!EMO[key]) {
          /* It said "Ignorado" and it was not ignored: the code went on into
             seg.mood carrying the gloss "?", and buildXml joined those
             glosses into also="?" — a literal question mark printed into the
             deliverable, announced by a `note` saying the opposite. A
             misleading low-severity diagnostic is worse than none, because it
             reads as handled. Now it is discarded here, at `fix`, with a
             position, and no `?` can reach the XML under any input. */
          G("fix", "humor fora da tabela",
            "<code>/" + esc(tk.v) + "/</code> não está na tabela de emoções. Descartado.",
            "UnknownEmotion",
            "mood off-table",
            "<code>/" + esc(tk.v) + "/</code> is not in the emotion table. Discarded.",
            tk);
          break;
        }
        var rec = { name:key, gloss:EMO[key], order:tk.order };
        var t4 = top(); if (t4) t4.emotions.push(rec);
        seg.mood.push(rec);
        break;
      }

      case "extend": {
        pendingOrigin = "extend";
        var nx2 = tokens[i+1];
        if (!nx2 || (nx2.k !== "open" && nx2.k !== "bareTag" && nx2.k !== "literal" && nx2.k !== "text"))
          G("fix", "pendurado", "<code>-</code> sem cadeia. Ex.: <code>[rw-cr</code>.", "DanglingChain",
          "dangling", "<code>-</code> with no chain. E.g. <code>[rw-cr</code>.");
        break;
      }
      /* `/` in a chain position, and the abandoned `\emo\` spelling. Both
         are refused by name rather than swallowed: an empty slot does not
         block, but that protects information that is MISSING, never
         information that is MALFORMED. Bucket N, `fix`, with a position. */
      case "badslash":
        G("fix", "barra na cadeia",
          "<code>/</code> dentro de uma cadeia. O divisor foi removido em v1.7 (C-01) e " +
          "<code>/</code> agora delimita apenas emoção. Feche a cadeia antes: <code>[in-rwk]/eth/</code>.",
          "SlashInChain",
          "slash in chain",
          "<code>/</code> inside a chain. The divider was removed in v1.7 (C-01) and " +
          "<code>/</code> now delimits emotion only. Close the chain first: <code>[in-rwk]/eth/</code>.",
          tk);
        break;
      case "badmood":
        G("fix", "grafia abandonada",
          "<code>\emo\</code> foi substituída por <code>/emo/</code> em v1.7 (I-19). " +
          "Escreva <code>/eth/</code>.",
          "BackslashMood",
          "abandoned spelling",
          "<code>\emo\</code> was replaced by <code>/emo/</code> in v1.7 (I-19). " +
          "Write <code>/eth/</code>.",
          tk);
        break;
      case "comma":  pendingOrigin = "item"; break;
      case "equals": { var t5 = top(); if (t5) t5.isDefinition = true; break; }
      case "semi":   closeSeg("semi"); break;

      case "linebreak": {
        /* `;;` FECHA o bloco, desde 2026-09-05.

           Ate aqui ele so marcava uma quebra visual e deliberadamente NAO
           fechava -- havia ate um diagnostico, LinebreakInsideBlock, dizendo
           isso ao Autor da Ordem. Medido, o desenho nao se sustentava: tudo
           caia num <block> so, o <break/> ia parar DEPOIS dele em vez de
           entre os dois, a volta reescrevia `;;` no fim do documento, e a
           queima descartava a marca inteira. Existia no alto nivel e nao
           significava nada no baixo.

           O Regente decidiu conserta-lo em vez de aposenta-lo, e a razao e
           o que o torna uma arteria: formatar uma Ordem longa depende de
           quebrar blocos, e um grafo de logica longo e a utilidade publica
           da ferramenta. `;` continua sendo o separador de segmento; `;;` e
           o separador que tambem MARCA a quebra, e agora os dois fecham.

           `seg.breaks` ja era emitido depois do bloco -- que era o lugar
           errado enquanto o bloco nao fechava, e passa a ser o certo agora
           que ele fecha: o <break/> cai entre um bloco e o proximo. */
        seg.breaks++;
        closeSeg("linebreak");
        break;
      }

      case "mode": {
        if (tk.v === "OFF") {
          var mn = { mode:"off", children:[], tok:tk };
          var t6 = top(); if (t6) t6.children.push(mn); else seg.children.push(mn);
          seg.pendingMode = mn;
        } else seg.pendingMode = null;
        break;
      }
      case "modeUnclosed":
        G("note", "modo texto", "<code>[off]</code> sem <code>[on]</code>. Resto lido como prosa.", "UnclosedOffMode",
          "text mode", "<code>[off]</code> without <code>[on]</code>. The rest is read as prose.");
        break;
      case "raw": {
        var rawNode = { literal:true, v:tk.v, form:"raw", tok:tk };
        if (seg.pendingMode) seg.pendingMode.children.push(rawNode); else seg.children.push(rawNode);
        break;
      }
      case "return": seg.isReturn = true; break;

      case "text": {
        var v = String(tk.v).trim();
        if (!v) break;
        var t7 = top();
        var txt = { text:true, v:v, tok:tk };
        if (t7) t7.children.push(txt); else seg.children.push(txt);
        if (/^(if|or|else|and|then|unless|se|ou|senao|entao)$/i.test(v))
          G("note", "palavra solta",
            "<code>" + esc(v) + "</code> solto. Lógica: <code>[if</code> <code>[unls</code> <code>[logic]</code>.", "LooseKeyword",
          "loose word", "<code>" + esc(v) + "</code> on its own. Logic: <code>[if</code> <code>[unls</code> <code>[logic]</code>.");
        /* A loose word that exists in the vocabulary is almost always a
           command written without `[`. Without this it becomes <off>,
           inert prose: the `rd` in a long query vanishes with no warning
           at all. */
        else if (/^[A-Za-z][A-Za-z0-9_.]*$/.test(v)) {
          var uw = v.toUpperCase(), lw = v.toLowerCase();
          var known = INSTR[uw] || ALIAS[uw] || STRUCT[uw] || META[uw] ||
                      (opts.session !== false && SESSION[lw]);
          if (known)
            G("ask", "comando solto",
              "<code>" + esc(v) + "</code> está no vocabulário mas foi escrito sem <code>[</code> — " +
              "virou prosa (<code>&lt;off&gt;</code>), não comando. Queria <code>[" + esc(lw) + "</code>?", "LooseCommandWord",
          "loose command", "<code>" + esc(v) + "</code> is in the vocabulary but was written without <code>[</code> — " + "it became prose (<code>&lt;off&gt;</code>), not a command. Did you mean <code>[" + esc(lw) + "</code>?");
        }
        if (/^\.+$/.test(v))
          G("note", "ponto solto",
            "<code>.</code> sem função. Separadores: <code>,</code> <code>;</code> <code>;;</code>.", "LooseDots",
          "loose dot", "<code>.</code> has no function here. Separators: <code>,</code> <code>;</code> <code>;;</code>.");
        break;
      }
    }
  }
  closeSeg("eof");

  // ---- template expansion ----
  // Before the other passes on purpose: valency, contradiction and empty
  // slot must see the expanded body, not the bare call.
  expandInvocations(segments, opts, G, parse);

  // ---- empty template slot ----
  segments.forEach(function (sgx) {
    walk(sgx.children, function (nd2) {
      if (nd2.canonical !== "PH") return;
      var nameNode = (nd2.children || []).filter(function (c) { return c.slotName; })[0];
      var q = (nd2.children || []).filter(function (c) { return c.literal; })[0];
      G("ask", "casa vazia",
        (nameNode ? "<code>" + esc(nameNode.raw) + "</code> " : "") +
        (q ? esc(q.v) : "sem resposta"), "PlaceholderPending",
          "empty field", (nameNode ? "<code>" + esc(nameNode.raw) + "</code> " : "") + (q ? esc(q.v) : "no answer"));
    });
  });

  // ---- deep nesting in a long block ----
  // A `[` without a `]` nests inside the previous one. After a few
  // commands this stops being refinement and becomes scope nobody asked for.
  segments.forEach(function (sgd) {
    var deepest = null;
    walk(sgd.children, function (nd2) {
      if (nd2.depth === undefined) return;
      if (!deepest || nd2.depth > deepest.depth) deepest = nd2;
    });
    if (deepest && deepest.depth >= LIMITS.nesting) {
      var chain = [], p = deepest;
      while (p && chain.length < 4) { chain.unshift(String(p.canonical || "?").toLowerCase()); p = p.parent; }
      G("note", "muito fundo",
        (deepest.depth + 1) + " níveis de aninhamento (…" +
        chain.map(function (x) { return "<code>[" + esc(x) + "</code>"; }).join(" › ") +
        "). Cada <code>[</code> sem <code>]</code> entra dentro do anterior — se a intenção era " +
        "sequência e não escopo, feche com <code>]</code> ou separe com <code>,</code>.", "DeepNesting",
          "very deep", (deepest.depth + 1) + " levels of nesting (…" + chain.map(function (x) { return "<code>[" + esc(x) + "</code>"; }).join(" › ") + "). Every <code>[</code> without <code>]</code> goes inside the previous one — if you meant a sequence and not a scope, close it with <code>]</code> or separate with <code>,</code>.");
    }
  });

  // ---- mandatory name for SECTION / BLOCK ----
  segments.forEach(function (sgn) {
    walk(sgn.children, function (nd2) {
      if (!NAMED_STRUCT[nd2.canonical]) return;
      var firstReal = (nd2.children || []).filter(function (c) {
        return c.literal || c.canonical || c.logic || c.template || (c.text && c.v);
      })[0];
      if (!firstReal || !firstReal.literal)
        G("fix", "sem nome",
          "<code>[" + esc(String(nd2.canonical).toLowerCase()) + "</code> exige um nome literal como primeiro slot. Ex.: <code>[" +
          esc(String(nd2.canonical).toLowerCase()) + "'nome',…</code>.", "MissingStructName",
          "no name", "<code>[" + esc(String(nd2.canonical).toLowerCase()) + "</code> needs a literal name as its first slot. E.g. <code>[" + esc(String(nd2.canonical).toLowerCase()) + "'name',…</code>.");
    });
  });

  // ---- valency ----
  if (opts.valency !== false) {
    segments.forEach(function (sg2) {
      walk(sg2.children, function (nd2) {
        if (!nd2.canonical || nd2.chainElement || nd2.slotName) return;
        if (nd2.canonical === "PH") return;
        if (nd2.tier === "unknown" || nd2.tier === "empty") return;

        /* strict positional arity takes precedence over FRAMES valency */
        var slots = SLOTS[nd2.canonical];
        if (slots) {
          var got = valueChildren(nd2).length + (nd2.colon ? 1 : 0);
          for (var k = got; k < slots.length; k++)
            G("ask", "falta operando",
              "<code>[" + esc(String(nd2.canonical).toLowerCase()) + "</code> exige " +
              slots.length + " termos, recebeu " + got + ". Falta <strong>" + esc(slots[k]) + "</strong>.", "MissingOperand",
          "operand missing", "<code>[" + esc(String(nd2.canonical).toLowerCase()) + "</code> takes " + slots.length + " terms, got " + got + ". Missing <strong>" + esc(slots[k]) + "</strong>.");
          return;
        }

        var frame = FRAMES[nd2.canonical];
        if (!frame) return;
        var filled = valueChildren(nd2).length + (nd2.colon ? 1 : 0);
        var want = frame[0];
        if (filled === 0)
          G("ask", "sem alvo",
            "<code>[" + esc(String(nd2.canonical).toLowerCase()) + "</code>" +
            (PTBR[nd2.canonical] ? " (" + PTBR[nd2.canonical] + ")" : "") +
            ": <strong>" + esc(want.replace("*", "")) + "</strong>?", "UnfilledSlot",
          "no target", "<code>[" + esc(String(nd2.canonical).toLowerCase()) + "</code>" + (INSTR[nd2.canonical] ? " (" + INSTR[nd2.canonical] + ")" : "") + ": <strong>" + esc(want.replace("*", "")) + "</strong>?");
        else if (want.slice(-1) === "*" && filled === 1)
          G("note", "lista de um",
            "<code>[" + esc(String(nd2.canonical).toLowerCase()) + "</code> aceita n itens, recebeu 1. Liste com <code>,</code>.", "SingletonList",
          "list of one", "<code>[" + esc(String(nd2.canonical).toLowerCase()) + "</code> takes n items, got 1. List them with <code>,</code>.");
      });
    });
  }

  // ---- composition species (optional store) ----
  // Annotation only: it changes no diagnostic and no XML. A command being
  // composite is not a problem to report, it is a fact an .hgml emitter
  // needs — so it rides in the AST and nowhere else.
  if (expansionRegistry(opts)) {
    segments.forEach(function (sgx2) {
      walk(sgx2.children, function (nd2) {
        if (!nd2.canonical) return;
        var e = entryOf(nd2.canonical, opts);
        if (!e) return;
        nd2.species = e.species;
        nd2.compositionDepth = typeof e.depth === "number" ? e.depth : null;
      });
    });
  }

  // ---- semantic rules (pairs, order, preconditions) ----
  checkRules(segments, opts, G);

  // ---- template constraints (the shape each template promises) ----
  checkTemplateConstraints(segments, opts, G);

  /* ---- bindings ----
     One name, one result. Two commands naming the same result make every
     later reference ambiguous, and choosing one would be the silent wrong
     answer this release exists to remove. Raised here rather than in
     buildXml because a diagnostic belongs to the parse. */
  collectBindings(segments, G);

  // ---- templates ----
  var defd = {}, invoked = [];
  segments.forEach(function (sg3) {
    walk(sg3.children, function (nd3) {
      if (!nd3.template) return;
      if (nd3.isDef) {
        defd[nd3.template.toLowerCase()] = true;
        if (!(nd3.children || []).length)
          G("fix", "tpl vazio",
            "<code>[--" + esc(nd3.template) + "=</code> sem corpo.", "EmptyTemplateDefinition",
          "empty tpl", "<code>[--" + esc(nd3.template) + "=</code> has no body.");
      } else invoked.push(nd3.template);
    });
  });
  var known = templateRegistry(opts) || {};
  invoked.forEach(function (nm) {
    if (!defd[nm.toLowerCase()] && !known[nm.toLowerCase()] && !known[nm])
      G("note", "tpl indefinido",
        "<code>[--" + esc(nm) + "</code> não definido aqui. TPL não persiste entre sessões. Redefina: <code>[--" +
        esc(nm) + "=…</code>.", "UndefinedTemplate",
          "tpl undefined", "<code>[--" + esc(nm) + "</code> is not defined here. TPL does not persist between sessions. Redefine it: <code>[--" + esc(nm) + "=…</code>.");
  });

  var rank = { fix:0, ask:1, note:2 };
  gaps.sort(function (a, b) { return rank[a.sev] - rank[b.sev]; });
  gaps.forEach(function (g) { g.plain = stripTags(g.msg); });
  return { segments:segments, gaps:gaps, tokens:tokens };
}


/* ------------------------------------------------------------------ *
 * Bindings — a command's operand literal NAMES the command's result
 *
 * The Regent's rule, from glyph-variable-naming-system.pgml: "when a
 * command targets an object in context using text followed by orders, the
 * result is named after the input text". `[sum`organized`[itr-core[ctx]]]`
 * names the result `organized`; `[var`get_data`[...]]` is the explicit
 * spelling of the same thing, not a separate mechanism.
 *
 * Decidable and mechanical: a command binds when it has BOTH an operand
 * literal AND a bracketed nested command. A command carrying only a
 * literal (`[nt`x`]`) has no result to name, so it binds nothing and the
 * document does not fill up with names for text.
 *
 * Scope is the whole glyph-package, which is what the Regent's file says:
 * "variable exists in current glyph-package". So the pass runs over every
 * segment before a line is emitted, and a reference resolves to a binding
 * written later just as well as to one written earlier.
 * ------------------------------------------------------------------ */
export var BIND_NAME = /^[A-Za-z_][A-Za-z0-9_.-]*$/;

export function bindingOf(nd) {
  if (!nd || !nd.canonical || nd.slotName) return null;
  var kids = nd.children || [], lit = null, hasNest = false;
  for (var i = 0; i < kids.length; i++) {
    var c = kids[i];
    if (c.literal && c.form !== "raw" && !lit && c.role !== "result") lit = c;
    else if (c.canonical && !c.chainElement) hasNest = true;
  }
  var v = String(lit && lit.v != null ? lit.v : "").trim();
  if (!lit || !hasNest || !v) return null;
  /* A NAME, not prose. `[--germinate]` expands to `[skill`tree logic
     structure`[...]]`, and binding that sentence would put a pseudo-name in
     the document and let `ref` match on a coincidence of wording. The
     Regent's own examples are identifier-shaped -- `organized`, `get_data`
     -- and that is the shape a name has. */
  if (!BIND_NAME.test(v)) return null;
  /* the literal DECLARES the name, so it is not also a reference to it */
  lit.isBinder = true;
  return v;
}

export function collectBindings(segments, G) {
  var binds = {}, order = [];
  (segments || []).forEach(function (sg) {
    walk(sg.children, function (nd) {
      var name = bindingOf(nd);
      if (!name) return;
      if (binds[name]) {
        /* Two commands naming one result: the later reference cannot say
           which it means, and picking one would be the silent wrong answer
           this release exists to remove. */
        if (G) G("fix", "nome repetido",
          "<code>" + esc(name) + "</code> nomeia mais de um resultado — uma referência não pode dizer qual.",
          "DuplicateBinding",
          "name bound twice", "<code>" + esc(name) + "</code> names more than one result — a reference cannot say which.");
      } else { binds[name] = true; order.push(name); }
    });
  });
  return binds;
}
