/* GENERATED by build-skill.js from scripts/core/version.js at engine 3.6.9.07 — DO NOT EDIT BY HAND.
   Edit the source in the glyph repository and run: node scripts/build-skill.js */
/**
 * core/version.js — the engine's version, in one place.
 *
 * The changelog moves this number (`.guidelines/.changelog/README.md`); the
 * entry exports it, the skill builder stamps it, and the inverse compares an
 * incoming document's `engine=` against it. release.frontend.rules.minor —
 * no digit resets another.
 */
export var VERSION = "3.6.9.07";
